### ISSUE TITLE
About function hooking

### ISSUE THREAD

**Issue by ballballsun** [frida/frida#100]
I wrote a node.js method to hook 3 functions (A,B,C) at the same time.
```
Interceptor.attach(funcInModule, {
            onEnter: function (args) {
                console.log("\n=== Function <" + functionName +"> Entered Start ===");
                console.log("arg0 " + args[0]);
                console.log("arg1 " + args[1]);
                console.log("arg2 " + args[2]);
                console.log("arg3 " + args[3]);
                console.log("arg4 " + args[4]);
                console.log("arg5 " + args[5]);
                console.log("=== Function <" + functionName +"> Entered Success ===\n");
            },
            onLeave: function (retval) {
            }
        });
```

But I find that args[0] in those 3 functions are always the same, then I try the print the address out and find that, args[0] have the same address:

```
=== Function <A> Entered Start ===
arg0 0x6a0f76c0  // <<< same
arg1 0xa7a77087
arg2 0x7784b630
arg3 0xffffff78
arg4 0x6f26b370
arg5 0x68816070
=== Function <A> Entered Success ===
```

```
=== Function <B> Entered Start ===
arg0 0x6a0f76c0  // <<< same
arg1 0x76dc103e
arg2 0x7369d508
arg3 0xffffff78
arg4 0x6f26b580
arg5 0x68816070
=== Function <B> Entered Success ===
```

```
=== Function <C> Entered Start ===
arg0 0x6a0f76c0  // <<< same
arg1 0x7851fa18
arg2 0x78533ac8
arg3 0x76660418
arg4 0x785345b8
arg5 0x78520758
=== Function <C> Entered Success ===
```

Q1. Is it a normal behaviour?
Q2. ```console.log(args.length);``` cannot show the number of args. Any way to do that?

**Comment by oleavr** [comment]
This is normal. The first argument might be the same because either:
- It's the `this` (C++) / `self` (Objective-C / etc., i.e. different methods called on the same object.
- The function accepts 0 arguments, and you just happen to look at the same garbage value (less likely).
- The function uses a custom calling convention. `args[n]` assumes the default calling convention. For custom calling conventions you can use e.g. `this.context.eax` to access the register values directly, and `Memory.read*(this.context.sp, ...)` to read from the stack, etc.

Frida's Interceptor has no information about the number of arguments, because there is no such information available at the ABI level (and we don't rely on debug symbols). So if you want to use `Interceptor.replace()` you will need to know, and supply, such information, but `Interceptor.attach()` works on any function without knowing anything about it.

Cheers!

**Comment by ballballsun** [comment]
Thanks for your responsive and detailed reply :)
I may need time to digest it.
