### ISSUE TITLE
Failed to load script: remote Frida does not support the “runtime” option; please upgrade it

### ISSUE THREAD

**Issue by davidlr99** [frida/frida#1013]
Hey,
I try to debug the (decrypted) Instagram++ app. I successfully injected the FridaGadget.dylib and get the App to start on my non-jailbroken iPhone (with https://github.com/Naituw/IPAPatch). 
I also get the "Frida message" in the XCode console: 
`"2019-09-05 11:42:58.188077+0200 Instagram[1884:408639] Frida: Listening on 127.0.0.1 TCP port 27042"
`
When I try to load Frida with "frida -U Gadget", I get following error message: 
`Failed to load script: remote Frida does not support the “runtime” option; please upgrade it`
Screenshot: https://imgur.com/a/cYuZ8Vr

Is there any workaround, or did I made a mistake somewhere? 

Best Regards,
David

**Comment by oleavr** [comment]
Hi,

This means FridaGadget.dylib is outdated. Updating it should solve this issue.

**Comment by mohsen-farahani** [comment]
Hi,
I have the same problem and it was not solved by updating

**Comment by oleavr** [comment]
Oops, thanks, will investigate. This sounds like a regression.

**Comment by nikolaflock** [comment]
Getting:
Attaching...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File ```
"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/frida_tools/application.py", line 523, in _run
    work()
  File "/usr/local/lib/python2.7/site-packages/frida_tools/application.py", line 301, in _try_start
    self._start()
  File "/usr/local/lib/python2.7/site-packages/frida_tools/repl.py", line 125, in _start
    self._update_status("Failed to load script: {error}".format(error=e))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 34: ordinal not in range(128)
```
Also on non-jailbroken iOS, also injecting Instagram app.

**Comment by baptx** [comment]
@davidlr99 what do you mean by decrypted? It looks like Instagram app is not compatible with Frida: https://github.com/frida/frida/issues/845

**Comment by oleavr** [comment]
## @davidlr99

> Failed to load script: remote Frida does not support the “runtime” option; please upgrade it

This is finally [fixed](https://github.com/frida/frida-tools/commit/cfefd204062d3be18b901e5b9cf7d23833974f9b) in frida-tools 6.0.0.

Note that this error means you have injected a FridaGadget.dylib that is really old. You're in luck though, as there is no longer any need to patch the app to add Gadget to it:

https://www.nowsecure.com/blog/2020/01/02/how-to-conduct-jailed-testing-with-frida/

## @nikolaflock

> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 34: ordinal not in range(128)

Also finally [fixed](https://github.com/frida/frida-python/commit/2488e35b1c90643c447e923b4bb60eaca7465b59) in Frida 12.8.5.

(This only affects Python 2, which is now EOL – recommend upgrading to Python 3.x.)

## Other issues?

Please make sure you're running Frida >= 12.8.5 on both host and target. We have fixed a lot of bugs since this issue was reported.

Thanks everyone for reporting bugs and helping make Frida better! 🙌
