### ISSUE TITLE
huawei p20 Unable to save SELinux policy to the kernel by frida-server 12.7.6

### ISSUE THREAD

**Issue by zxhubo** [frida/frida#1039]
huawei p20 has been root and unlock，but the selinux is Enforcing. I want to run frida-server 12.7.6 on this device, but it's failed. The error is  'Unable to save SELinux policy to the kernel: Out of memory' and the device is reboot.

**Comment by g33kyshivam** [comment]
I'm also facing the same issue for my Redmi Mi 4i rooted phone! Getting the same error `Unable to add SELinux rule ` Have raised the issue for the same here #1041

**Comment by zxhubo** [comment]
@oleavr only the author of frida can do it

**Comment by ikkisoft** [comment]
Same issue with a Huawei Mate 10 (running Android 10)

**Comment by zxhubo** [comment]
@ikkisoft Yes, if selinux can't be turn off , frida can't be useful

**Comment by ikkisoft** [comment]
> @ikkisoft Yes, if selinux can't be turn off , frida can't be useful

Yeah, I would need to get a modified kernel. Thanks!

**Comment by PLTorrent** [comment]
Same issue on Huawei P30 Pro. 

HWVOG:/ # id
uid=0(root) gid=0(root) groups=0(root) context=u:r:magisk:s0
HWVOG:/ # /data/local/tmp/abc-srv                                                                                                                                                          
Unable to save SELinux policy to the kernel: Out of memory
Segmentation fault 
139|HWVOG:/ # setenforce 0
setenforce: Couldn't set enforcing status to '0': Invalid argument
1|HWVOG:/ # getprop | grep selinux
[ro.boot.selinux]: [enforcing]
[ro.boottime.init.selinux]: [251]
[selinux.restorecon_recursive]: [/data/misc_ce/0]

Changing ro.boot.selinux to premissive does not change a thing. This prop is obsolete I think.

**Comment by miaochiahao** [comment]
> Same issue on Huawei P30 Pro.
> 
> HWVOG:/ # id
> uid=0(root) gid=0(root) groups=0(root) context=u:r:magisk:s0
> HWVOG:/ # /data/local/tmp/abc-srv
> Unable to save SELinux policy to the kernel: Out of memory
> Segmentation fault
> 139|HWVOG:/ # setenforce 0
> setenforce: Couldn't set enforcing status to '0': Invalid argument
> 1|HWVOG:/ # getprop | grep selinux
> [ro.boot.selinux]: [enforcing]
> [ro.boottime.init.selinux]: [251]
> [selinux.restorecon_recursive]: [/data/misc_ce/0]
> HWVOG:/ # /data/local/tmp/abc-srv --version
> 12.8.6
> 
> Changing ro.boot.selinux to premissive does not change a thing. This prop is obsolete I think.

Hi I'd like to root Huawei P30 Pro too, could you please tell me how to do it?

**Comment by oleavr** [comment]
Please open a PR on frida-website adding instructions on how to get Frida working on such devices. Thanks!

**Comment by icew4y** [comment]
> Same issue on Huawei P30 Pro.
> 
> HWVOG:/ # id
> uid=0(root) gid=0(root) groups=0(root) context=u:r:magisk:s0
> HWVOG:/ # /data/local/tmp/abc-srv
> Unable to save SELinux policy to the kernel: Out of memory
> Segmentation fault
> 139|HWVOG:/ # setenforce 0
> setenforce: Couldn't set enforcing status to '0': Invalid argument
> 1|HWVOG:/ # getprop | grep selinux
> [ro.boot.selinux]: [enforcing]
> [ro.boottime.init.selinux]: [251]
> [selinux.restorecon_recursive]: [/data/misc_ce/0]
> HWVOG:/ # /data/local/tmp/abc-srv --version
> 12.8.6
> 
> Changing ro.boot.selinux to premissive does not change a thing. This prop is obsolete I think.

You must modify the Huawei kernel source code and then recompile, and flash

**Comment by YsielX** [comment]
> > Same issue on Huawei P30 Pro.
> > HWVOG:/ # id
> > uid=0(root) gid=0(root) groups=0(root) context=u:r:magisk:s0
> > HWVOG:/ # /data/local/tmp/abc-srv
> > Unable to save SELinux policy to the kernel: Out of memory
> > Segmentation fault
> > 139|HWVOG:/ # setenforce 0
> > setenforce: Couldn't set enforcing status to '0': Invalid argument
> > 1|HWVOG:/ # getprop | grep selinux
> > [ro.boot.selinux]: [enforcing]
> > [ro.boottime.init.selinux]: [251]
> > [selinux.restorecon_recursive]: [/data/misc_ce/0]
> > HWVOG:/ # /data/local/tmp/abc-srv --version
> > 12.8.6
> > Changing ro.boot.selinux to premissive does not change a thing. This prop is obsolete I think.
> 
> You must modify the Huawei kernel source code and then recompile, and flash

How should I recompile the kernel. What code should I change?

**Comment by kindle4jerry** [comment]
Try to set CONFIG_SECURITY_SELINUX_DEVELOP=y and recompile the kernel.
Notice that: For kirin970, if you are in EMUI 9.1>=9.1.321, the system is read-only because Huawei uses EROFS file system.
Try to use EMUI<=9.1.312, the system is read-write after root.

May help your Huawei devices...@YsielX @zxhubo @ikkisoft @miaochiahao @oleavr 

Reference:
[https://github.com/kindle4jerry/honor-play-kernel-9.1-kindle4jerry](url)
[https://github.com/kindle4jerry/kernel-PAR-9.1.321](url)

**Comment by shikorido** [comment]
Just want to share with several points on how to solve it on your own even if custom kernel is not available (or closed source). You still need to give it much effort to accomplish. I will provide a kernel build guideline as well (in brief?).

## Precompiled sepolicy patch
A simple one by my opinion is to patch `precompiled_sepolicy` using [sepolicy inject for Android](https://xdaforums.com/t/setools-android-with-sepolicy-inject.2977563). After building (or downloading prebuilts) move them to your **device**. You are ready for patching now.

The file is usually in `/vendor/etc/selinux/` but also can be in `/system/etc/selinux/` or `/odm/etc/selinux/`. Execute `find / -name precompiled_sepolicy 2>/dev/null` to find any.

Copy to some working place and create backup just in case. After that execute `/path/to/sepolicy-inject -Z zygote -P /path/to/patched_precompiled_sepolicy` which makes zygote permissive so selinux just logs the denials but does not reject any actions from zygote. You can also specify `-o /path/to/output_file` but you should have a backup already.

Yes, you can make the permissions more granular instead of covering the whole source type as permissive, the choice is yours. Repeat the same `sepolicy-inject` actions by looking either in `dmsg` or `logcat` for frida-related denials. This is how my policies look after the process (permissive duplicates are fine if you have some):
```sh
> magiskpolicy --print-rules | grep permissive
permissive logserver
permissive mediaprovider
permissive system_app
permissive radio
permissive shell
permissive system_server
permissive untrusted_app
permissive crash_dump
permissive priv_app
permissive logserver
permissive nfc
permissive zygote
permissive untrusted_app_25
permissive untrusted_app_27
permissive platform_app
permissive magisk   # makes itself permissive, so do not add it by copy-paste
permissive irqbalance
```
Some of those are not frida-related but I leave it as-is.

Once you done with patching you have 4 (2 of them are too early/late) options to replace/bind-mount/overlay the file.

1. Replacing.
    The simplest one. Just replace if your ROM has no `RO` partitions. `cp /path/to/precompiled_sepolicy /vendor/etc/selinux/precompiled_sepolicy`

2. Bind-mount
    To be honest, this unlikely will work cause it might be too late (and it is). In my case this one did not work but I want to share. Use magisk's `post-fs-data` (the earliest thing magisk can offer) to bind-mount the file in-place.
    Should look like
    ```sh
    #!/system/bin/sh
    mount -o bind /path/to/patched_precompiled_sepolicy /vendor/etc/selinux/precompiled_sepolicy
    ```
    at `/data/adb/post-fs-data.d/precompiled_policy_bind_mount.sh`
    must be executable as well `chmod +x /data/adb/post-fs-data.d/precompiled_policy_bind_mount.sh`

3. Use `magiskboot` (build your own or use prebuilts) to unpack `boot.img`, `recovery_ramdisk.img` or `erecovery_ramdisk.img` which magisk had patched already (erecovery is more suitable for custom recoveries, do not use it for magisk).

    For boot.img/recovery.img execute `magiskboot unpack /path/to/boot_or_recovery.img`. I do not have experience with `boot.img` cause Huawei devices do not use `boot.img` and some ROMs lack explicit ramdisk partition (so magisk takes one recovery partition for itself to stay systemless).

    The one file you need after extraction is `ramdisk.cpio` which is kind of archive with its own files hierarchy. If you would like to view its contents, write `sudo magiskboot cpio /path/to/ramdisk.cpio "ls"`. Note that you should execute it as root and also more important note is that magiskboot's cpio takes command as a string, so always wrap it to quotes.

    Now you can use [overlay mechanism](https://topjohnwu.github.io/Magisk/guides.html#root-directory-overlay-system) to make magisk bind-mount anything you want. With its own limitations, for example, in the form of an exact moment and the mandatory existence of a file, cause it still uses `mount -o bind` (mount syscall) under the hood which makes sense only if the target exists.

    If you just place the file to `overlay.d/vendor/etc/precompiled_sepolicy` it would be too early. The filesystem more likely is not constructed yet, instead, prefer using custom `.rc` file to make bind-mount when the `/vendor` got mounted. This way you can inject it much earlier than using `post-fs-data`.

    You can insert the file you wrote using `magiskboot cpio ramdisk.cpio "add 750 overlay.d/my_custom.rc /path/to/my_custom.rc`. If you want to nest in directories, create the directories firstly:
    ```sh
    # E.g. we want to locate my_custom.rc to overlay.d/example_dir/
    # Has no sense cause magisk will ignore the file's overlaying if it does not exist, this is just an example.
    # Even though the docs say:
    # Each *.rc file (except for init.rc) in overlay.d will be read and concatenated AFTER init.rc if it does not exist
    # in the root directory, otherwise it will REPLACE the existing one.
    # I can't say if it refers only to overlay.d/*.rc files...
    magiskboot cpio ramdisk.cpio "mkdir 750 overlay.d/example_dir"
    magiskboot cpio ramdisk.cpio "add 750 overlay.d/example_dir/my_custom.rc /path/to/my_custom.rc"

    # Check with
    magiskboot cpio ramdisk.cpio "ls -r" | grep overlay.d
    ```
    The removal process should be performed in reverse order in ideal.

    Now this is how the actual `very_early_sepol_inject.rc` file could look like:
    ```sh
    # Within init binary SELinux loads precompiled_sepolicy, so it is late
    # Cause magisk injects the .rc file in the end of the init.rc
    # The best we can is to use the early-init stage
    on early-init
        mount none /sbin/precompiled_sepolicy_PATCHED /vendor/etc/selinux/precompiled_sepolicy bind
    ```
    Adding to the `ramdisk.cpio`:
    ```sh
    magiskboot cpio ramdisk.cpio "add 750 overlay.d/very_early_sepol_inject.rc /path/to/very_early_sepol_inject.rc"
    magiskboot cpio ramdisk.cpio "add 644 overlay.d/sbin/patched_precompiled_sepolicy /path/to/patched_precompiled_sepolicy"
    ```

    But here is an issue. The SELinux contexts got loaded very early before any `*.rc` files execution. So we go to the 4 point.

4. The only viable way to inject custom precompiled_sepolicy before `init` issues SELinux to load them is to patch either magisk's patched `init` (called `magiskinit` in the dmesg logs and it is the same file as in `/sbin/magiskinit`) or the default `init` binary that locates in `/init` after filesystem construction. What about images (e.g. `SYSTEM.img`), depending on SAR/SAS `init` will be located in different places within the system image but we won't consider that cause we are under `EROFS` anyway).

    The simple approach is to patch the system's init by replacing `/vendor/etc/selinux/precompiled_sepolicy` to something like `/sbin/precompiled_sepolicy` using HxD by filling the remaining bytes with `0x00` (the end of the string is indicated by zero byte, so the strings are called `Zero Terminated` or `Null Terminated`). The magisk is not bind-mounting `/init` in place as we could thought, instead, it runs the overlayed `init`. Idk why it was not documented well enough (or I am blind, whatever) cause I was tried to examine why `/init` stays unchanged even though the patched version is running.

    The full solution could look like:
    ```sh
    # Add patched init to execute instead of /init
    magiskboot cpio /path/to/ramdisk.cpio "add 750 overlay.d/init /path/to/patched_init"

    # Add patched precompiled sepolicy to overlay.d/sbin along with precompiled_sepolicy.plat_and_mapping.sha256
    # cause SELinux initialization requires that file to stay along with precompiled_sepolicy.
    # You don't need to patch or change it at any sense, just copy-paste.
    # A little sidenote: if you add precompiled_sepolicy_PATCHED to overlay, you should follow the name
    # and have precompiled_sepolicy_PATCHED.plat_and_mapping.sha256 along with.
    magiskboot cpio /path/to/ramdisk.cpio "add 750 overlay.d/sbin/precompiled_sepolicy /path/to/patched_precompiled_sepolicy"
    magiskboot cpio /path/to/ramdisk.cpio "add 750 overlay.d/sbin/precompiled_sepolicy.plat_and_mapping.sha256 /path/to/precompiled_sepolicy.plat_and_mapping.sha256"

    # Repacking ready to flash image
    magiskboot repack /path/to/initial_magisk_patched/boot_or_recovery.img repacked_boot_or_recovery.img

    # Adb/flash/etc.
    adb push /path/to/repacked_boot_or_recovery.img /sdcard
    adb shell
    su
    dd if=/sdcard/repacked_boot_or_recovery.img of=/dev/block/by-name/BOOT_OR_RECOVERYRAMDISK bs=4096
    reboot
    ```

    The possible caveat you can encounter is insufficient space after adding ~750KB `overlay.d/sbin/precompiled_sepolicy` and ~2.3MB `overlay.d/init` files. You can use the following file to examine the most-sized files to remove them from `ramdisk.cpio`:
    ```sh
    #!/usr/bin/env bash
    # find_most_sized_files.sh
    # This one will concatenate decimal size with unit letters together to use sort -h
    sudo magiskboot cpio ramdisk.cpio "ls -r" | awk '{ print $1 " " $2 " " $3 " " $4 $5 " " $6 " " $7 }' | sort -rhk 4 | head -20
    ```
    And
    ```sh
    chmod +x find_most_sized_files.sh
    ./find_most_sized_files.sh
    # top of huge files
    mkdir -p extracted/path/to/extract
    sudo magiskboot cpio ramdisk.cpio "extract path/to/huge_file extracted/path/to/extract/huge_file"
    # Be careful to not delete some necessary files
    sudo magiskboot cpio ramdisk.cpio "rm path/to/huge_file"
    ```
    The files I have removed to fit the patched files to image:
    ```
    extracted
    ├── dload
    │   └── update_huawi_dload.zip  # 1.5MB
    └── res
        └── fonts
            └── DroidSansFallback.ttf  # 3MB
    ```
    If you flash the slightly larger image it won't boot and instead will show you something like "Recovery is corrupted". Go to erecovery/fastboot (or even factory fastboot if something was messed up) and reflash the working image.
    Always check the repacked image size against the initial image. They must be equal.

    Debug actions to check what was happened upon boot will consist from awaiting adbd initialization early enough to collect dmesg logs:
    ```
    # Immediately after adbd was started (on bootanimation in general)
    adb shell
    su
    # To order output conveniently, from many to few
    dmesg | grep init
    dmesg | grep magisk
    dmesg | grep sepolicy
    ```

## Kernel build
This one is definetely harder in some sense but is simple enough cause you just need to modify merge_config file for `CONFIG_SECURITY_SELINUX_DEVELOP=y` and other useful stuff. The only tricky thing is automating the cleanup/build process using self-written scripts.

Since the thread is Huawei related and my device is `Honor 8X`, I will assume you also have rooted Huawei device so try to find appropriate kernel sources for your ROM at [Huawei Open Source](https://consumer.huawei.com/en/opensource/) by using the model name (like `Honor 8X`). Mine was matched up to `JSN` thing so I can't say if I could use `ARE_PIE_EMUI9.1.0` with `EMUI9.1` but I think it would be fine.

After downloading and extracting the codebase, go to the `kernel/` folder which is the one we are interested in. Next find the merge config you will change. Look for the `arch/<yours_arch>/configs/merge_<SoC>_defconfig` file. Mine is `arch/arm64/configs/merge_kirin710_defconfig` and I have copied it to `arch/arm64/configs/mine_merge_kirin710_defconfig` to not touch the main one.

After that use any text-editor and locate the `CONFIG_SECURITY_SELINUX` lines. If you see
`# CONFIG_SECURITY_SELINUX_DEVELOP is not set`
this means the value for this entry is `n`. To enable, change it to
`CONFIG_SECURITY_SELINUX_DEVELOP=y`
This one change will be enough to expose `setenforce 0` to be able to set `Permissive` SELinux state.

You can go further and disable more Huawei's hardenings by configuring:
```kconfig
CONFIG_HISI_SELINUX_EBITMAP_RO=n
CONFIG_HISI_SELINUX_PROT=n
CONFIG_HUAWEI_SELINUX_DSM=n
CONFIG_HISI_RO_LSM_HOOKS=n
CONFIG_HUAWEI_HIDESYMS=n
CONFIG_HUAWEI_PROC_CHECK_ROOT=n
CONFIG_HW_ROOT_SCAN=n
CONFIG_HISI_EARLY_RODATA_PROTECTION=n
```

You can also disable option by using the following:
`# CONFIG_HISI_PMALLOC is not set`
This is not a comment but the special form. Note that if you are diving in.

What about the main issue many of you and me encounter `Unable to save SELinux policy to the kernel: Out of memory`. It goes to the `CONFIG_HISI_MM`, or more precisely, to `CONFIG_HISI_PMALLOC`. I will give you descriptions of these two in `Kconfig`:
```kconfig
menuconfig HISI_MM
	bool "Hisilicon MM support"
	---help---
	  This option add some hisilicon mm codes, needed by following modules.

if HISI_MM

config HISI_PMALLOC
	bool "Protectable Memory Allocator"
	default y
	depends on MMU
	depends on HISI_MM
	select  GENERIC_ALLOCATOR
	help
	It allows to write-protect variables allocated dynamically
	ls /sys/kernel/pmalloc

...
```
Here is what the `/sys/kernel/pmalloc/selinux/` (`selinux` is the only node) contains:
```
> /sys/kernel/pmalloc/selinux # ls
avail chunks protected size
> /sys/kernel/pmalloc/selinux # cat avail
208336
> /sys/kernel/pmalloc/selinux # cat chunks
1
> /sys/kernel/pmalloc/selinux # cat protected
ro_protected
> /sys/kernel/pmalloc/selinux # cat size
4198400
```
So the `CONFIG_HISI_PMALLOC` denies the `magiskpolicy --live "allow zygote magisk process *"` kind of actions. If I leave `CONFIG_HISI_MM` it works fine, but as soon as the `CONFIG_HISI_PMALLOC` is enabled it gets rejected.

Once you setted up options you need, the quirk part begins: `build`. I would recommend you to download `aarch64-linux-android-4.9` prebuilt or some other mentioned in `README_Kernel.txt` located at the root of extracted sources.

You more likely can compile it using the modern gcc versions like 14 ones but you would need to modify `Makefile` to disable treatment of some warning as errors and make other changes if necessary. I could build the kernel for my device with `aarch64-linux-gnu` crosscompile package which has 14.2.0 version (debian) but it is better to stick with good old time-tested toolchains.

A bit of sidetopic. If you want to build the kernel using clang (and your kernel sources was not designed for the kind of task), you would need to change/patch/rewrite some pieces of code. I have tried that and successfully built the kernel in the end. I spend quite a few time but in the end the kernel was not even bootable. It could not proceed to `bootanimation` and rebooted to `erecovery`. Other combinations like `CC="clang $(CLANG_TARGET)" LD=$(CROSSCOMPILE)ld` and `CC=$(CROSSCOMPILE)gcc LD=ld.lld LDFINAL_vmlinux=$(CROSSCOMPILE)ld` build without errors as well but the output kernel still was not bootable). Will investigate the behaviour further...

Once you downloded the prebuilts, place it to somewhere. I would recommend `/opt/toolchains/<downloaded_toolchain_name>` or even `/opt/toolchains/gcc/<downloaded_toolchain_name>`. Mine was `/opt/toolchains/aarch64-linux-android-4.9`. If the host has newer gcc versions installed, they may emit `warnings as errors` because of enhanced analysis algorithms and this could be a bit of pain in the ass if you are a beginner in that stuff. You can say `"Do not consider the warning as the error"` using `-Wno-error=int-conversion` for example. Lets hope you will not encounter with it.

Now you can have the following simple files to cleanup/build (these are provided for my device, change arch and target to match against your kernel sources):
The `myClean.sh` script:
```sh
#!/usr/bin/env bash
make ARCH=arm64 distclean $@
rm -rf ../out
```
The `myBuild.sh` script:
```sh
#!/usr/bin/env bash
export PATH=/opt/toolchains/aarch64-linux-android-4.9/bin:$PATH
# Target specification
export CROSS_COMPILE=aarch64-linux-android-
# Maybe your kernel was built using clang, who knows
export CLANG_TRIPLE=aarch64-linux-android

# Host related (can be omitted to leave defaults).
export HOSTCC=gcc
export HOSTCXX=g++
export HOSTLD=ld

# You do not need to copy merge config to kernel/
# The build system will locate appropriate config by looking at arch/<arch>/configs/$MERGEFILE
MERGEFILE=mine_merge_kirin710_defconfig
echo "Performing clean first"
./myClean.sh #V=1    # V=1 is a verbose mode

mkdir -p ../out
make ARCH=arm64 O=../out $MERGEFILE V=1  #LLVM=1 LLVM_IAS=1    # Some kernels might have the LLVM args as well for clang
make ARCH=arm64 O=../out -j2 V=1  #LLVM=1 LLVM_IAS=1

echo "Done."
```

The built kernel will be located in `../out/arch/arm64/boot/Image` (along with `Image.gz` to skip the compression using `-n` flag for `magiskboot`, but whatever).

And remember. Do not touch the `../out/arch/arm64/boot/dts`. It is board-specific and already baked into separated partitions like `DTS.img` which actually contains `DTB` (to get `DTS` use `dtc -I dtb -O dts extracted_DTS DTS.txt`) and `DTO.img` which actually contains `DTBO` (to get `DTSO` use `dtc -I dtb -O dts extracted_DTBO DTSO.txt`).
I had a bad experience trying to pull those to my device and got hard-brick which was revived by Android Utility which rebooted the device into Factory Bootloader.

The kernel repack process is quite simple:
```sh
magiskboot unpack /path/to/stock_kernel.img
mv kernel kernel_stock
cp /path/to/built_kernel kernel
magiskboot repack /path/to/stock_kernel.img built_kernel.img

# Adb/flash/etc.
adb push built_kernel.img
su
dd if=/sdcard/built_kernel.img of=/dev/block/by-name/kernel bs=4096
reboot
```



Finally, I want to say that I use `EMUI9.0` ROM that has no RO partitions but I was interested in the ways of injecting patched `precompiled_sepolicy` if we are locked down with closed source kernel or `EROFS` partitions. The magisk version I use is [Kitsune Magisk](https://github.com/1q23lyc45/KitsuneMagisk/releases) which struggles in updates because of Magisk's transition to RUST. The `EMUI9.1` has a poor `EROFS` implementation so the erofs utilities can't properly extract it to make new `RW` images. I was tried. And I can't guarantee if it would work even if no errors were encountered during the extraction process.

And I know that some of you are stuck with `EMUI9.1` cause the device lacks `EMUI9.0` and thats lead to encryption that might be very inconvenient for the root users. Probably the magisk's `overlay.d` tricks can be used to find the proper solution to disable force encryption.

In the end, the more aggressive patches can be applied either to `magiskinit` or `init` to make it behave the way you want.

Please feel free to point out any errors so I can correct them. I hope this helps someone who is looking for an answer but can't find any useful information like I once did.

**Comment by shikorido** [comment]
There may be other hardenings that prevent writing to `/sys/fs/selinux/load`. It seems to allow/deny randomly after some time after boot. Denials happen much more often than allowances.

While on `bootanimation` even the wrong rule can be used without any timeouts. Once the device is booted to lockscreen it reinitializes USB gadget and adb loses the connection.

So now when we try to use the wrong policy (like using a non-existent type) we get a timeout. Not sure what exactly causes this. Over time or at some point the denials appear almost every time.

Thats definetely should be investigated further. Will try to find something interesting again.


What about `ramdisk.cpio` shenanigans. I know, this approach is old indeed. Magisk supports `sepolicy.rule` which got executed at `magiskinit` before the real `init` execution starts hence it can add any kind of SEPolicy rule.

I was trying to find a solution using `precompiled_sepolicy` patching. It can be further expanded to the case when no `precompiled_sepolicy` is found (changing location to non-existent files) to force the policies recompilation using `.cil` files but it has no sense at all, just a possibility.

The one more thing I am curious about is the magisk's `early-mount`:
```
[   17.378356] [pid:1,cpu7,init]magiskinit: access .magisk/preinit/magisk-wifiadb/early-mount failed with 2: No such file or directory
[   17.491607] [pid:1,cpu6,init]magiskinit: access /data/.magisk/preinit/magisk-wifiadb/sepolicy.rule failed with 2: No such file or directory
```
Since there is a `/sbin/.magisk/early-mount.d/init.d/` folder, it may be related to `*.rc` files that are either for `overlay.d` or something else. I tend to think it is for `overlay.d`. Please don't kick me for my poor knowledge.
