### ISSUE TITLE
"Target process terminated." on El Capitan (Process is still running)

### ISSUE THREAD

**Issue by tosbaha** [frida/frida#105]
I am running latest Frida (6.2.4) on El Capitan 10.11.3 (15D21). I updated to latest version of frida

> sudo easy_install -U frida

I used frida-trace to attach Mac app on El Capitan. It successfully found the functions and it said

> Started tracing 2 functions. Press Ctrl+C to stop.

After a while, I saw

> Target process terminated.

Even though program was still running and functioning.

I tried to attach both with API name and ObjC method name

>  frida-trace -m "+[RNDecryptor decryptData:withPassword:error:]" Appname
> frida-trace -i "CCCrypt*" Appname

It always exists after a while. It seems like when it reaches those functions, it exists. Is there anything that I can do to debug this issue? Thanks.

**Comment by tfoldi** [comment]
I have the same issue on El Capitan

**Comment by tfoldi** [comment]
After disabling SIP it's working fine for me: http://www.macworld.com/article/2986118/security/how-to-modify-system-integrity-protection-in-el-capitan.html

Strange, because I do not run anything under root user and I was able to debug for a few seconds.

Whatever, with SIP disabled it works fine for me.

**Comment by oleavr** [comment]
Fixed in latest Frida 9.x.
