### ISSUE TITLE
Where I could check Javascripts API?

### ISSUE THREAD

**Issue by pgw00k** [frida/frida#1145]
Hello,everyone,I am a newer frida user,I want to know where I could find the all api about Javascripts?

just like Memory.readUtf8String I can't find some document about that,maybe there function can read a Int/Float?

**Comment by oleavr** [comment]
You can find it at:
https://frida.re/docs/javascript-api/

And as inline docs in VS Code or another editor that supports TypeScript. Here's how to get started:
https://github.com/oleavr/frida-agent-example

The API you mentioned isn't in the docs because it's deprecated. Use the `.readUtf8String()` method on NativePointer instead.
