### ISSUE TITLE
Error when building Makefile.sdk.mk on Android arm64

### ISSUE THREAD

**Issue by shadowslasher410** [frida/frida#1178]
I'm trying to build Makefile.sdk.mk on my Android (arm64). I get the following error when trying to 'make' it (note that I do have m4 version 1.4.18 installed):
```
# make -f Makefile.sdk.mk
. build/fs-env-linux-arm64.rc && cd xz && [ -f autogen.sh ] && NOCONFIGURE=1 ./autogen.sh || autoreconf -ifv
+ autopoint -f
autom4te: need GNU m4 1.4 or later: /home/buildbot/frida/build/ft-toolchain-linux-x86_64/bin/m4                       + libtoolize -c -f
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
+ aclocal -I /data/data/com.termux/files/home/frida/build/fs-linux-arm64/share/aclocal -I /data/data/com.termux/files/home/frida/build/fs-toolchain-linux-arm64/share/aclocal -I m4
autom4te: need GNU m4 1.4 or later: /home/buildbot/frida/build/ft-toolchain-linux-x86_64/bin/m4
aclocal: error: echo failed with exit status: 1
autoreconf: Entering directory `.'
autoreconf: running: autopoint --force
autom4te: need GNU m4 1.4 or later: /home/buildbot/frida/build/ft-toolchain-linux-x86_64/bin/m4
autoreconf: running: aclocal -I /data/data/com.termux/files/home/frida/build/fs-linux-arm64/share/aclocal -I /data/data/com.termux/files/home/frida/build/fs-toolchain-linux-arm64/share/aclocal --force -I m4
autom4te: need GNU m4 1.4 or later: /home/buildbot/frida/build/ft-toolchain-linux-x86_64/bin/m4
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1
make: *** [Makefile.sdk.mk:279: xz/configure] Error 1
```

**Comment by oleavr** [comment]
Hmm, I see multiple issues that we need to fix:
- Misdetected OS, it detected `linux` when it should have detected `android`
- Misdetected architecture, i.e. `releng/detect-arch.sh` detected `x86_64` when it should have detected `arm64`

These two issues means it downloaded the prebuilt toolchain for `linux-x86_64`.

You will also need to build the toolchain for `android-arm64`. The easiest is probably cross-compiling it from a Linux or macOS system. Something like:

```sh
$ make -f Makefile.toolchain.mk FRIDA_HOST=android-arm64
```

Then you can transfer the tarball to your Android device at `build/toolchain.tar.bz2`. (Once you can confirm that it builds and works correctly, I can reproduce it on my end and upload the resulting tarball to `build.frida.re`.)

**Comment by shadowslasher410** [comment]
Hmm... that doesn't work either... Here's the error I get when trying to build the toolchain (just so you know, i'm using the TSU (https://github.com/cswl/tsuwrapper) for Termux (https://termux.com/), if that makes any difference).
```
make -f Makefile.toolchain.mk FRIDA_HOST=android-arm64
FRIDA_HOST=android-arm64 \
        FRIDA_OPTIMIZATION_FLAGS="-Os" \
        FRIDA_DEBUG_FLAGS="-g3" \
        FRIDA_EXTRA_LDFLAGS="-Wl,--version-script,/data/data/com.termux/files/home/frida/build/ft-executable.version" \
        FRIDA_ASAN=no \
        FRIDA_ENV_NAME=ft \
        FRIDA_ENV_SDK=none \
        ./releng/setup-env.sh
make: *** [Makefile.toolchain.mk:274: build/ft-env-android-arm64.rc] Error 1
```

**Comment by shadowslasher410** [comment]
So I tried to build the toolchain on my Linux VM, but i'm getting another error
```
make: *** No rule to make target 'build/ft-tmp-android-arm64/.package-stamp', needed by 'build/toolchain-android-arm64.tar.bz2'.  Stop.
```

**Comment by shadowslasher410** [comment]
okay, so now I'm getting these errors:
```
ANDROID_NDK_ROOT=/opt/android-ndk-r21 make -f Makefile.toolchain.mk FRIDA_HOST=android-arm64
In file included from ../../../../m4/lib/freading.c:22:
../../../../m4/lib/stdio-impl.h:72:22: error: field has incomplete type 'struct __sbuf'
      struct  __sbuf _ub; /* ungetc buffer */
                     ^
../../../../m4/lib/stdio-impl.h:72:15: note: forward declaration of 'struct __sbuf'
      struct  __sbuf _ub; /* ungetc buffer */
              ^
../../../../m4/lib/freading.c:40:16: error: no member named '_flags' in 'struct __sFILE'
  return (fp_->_flags & __SRD) != 0;
          ~~~  ^
../../../../m4/lib/freading.c:40:25: error: use of undeclared identifier '__SRD'
  return (fp_->_flags & __SRD) != 0;
                        ^
3 errors generated.
Makefile:1910: recipe for target 'freading.o' failed
make[4]: *** [freading.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory '/home/sheryl/frida/build/ft-tmp-android-arm64/m4/lib'
Makefile:1674: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/home/sheryl/frida/build/ft-tmp-android-arm64/m4/lib'
Makefile:1572: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/sheryl/frida/build/ft-tmp-android-arm64/m4'
Makefile:1528: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/sheryl/frida/build/ft-tmp-android-arm64/m4'
Makefile.toolchain.mk:220: recipe for target 'build/ft-android-arm64/bin/m4' failed
make: *** [build/ft-android-arm64/bin/m4] Error 2
```

**Comment by oleavr** [comment]
@shadowslasher410 Hmm, well, it sounds like we need more patches in `releng/patches`. But I wouldn't recommend going down that rabbit-hole now unless you're prepared for some pain. (Bumping to a newer NDK tends to be painful.)

**Comment by shadowslasher410** [comment]
@oleavr I tried to use r21 instead of r20 because when I tried to use r20 I get this error
```
configure: error: in `/home/sheryl/frida/build/ft-tmp-android-arm64/m4':
configure: error: C preprocessor "/opt/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang -E" fails sanity check
See `config.log' for more details
Makefile.toolchain.mk:220: recipe for target 'build/ft-tmp-android-arm64/m4/Makefile' failed
make: *** [build/ft-tmp-android-arm64/m4/Makefile] Error 1
```
if needed, I posted the contents of config.log at https://pastebin.com/PGkvjYin

**Comment by Grimler91** [comment]
I gave compiling on device a try but also gave up fairly quickly. 

I have however managed to cross-compile the python bindings for [all arches in termux](https://github.com/termux/termux-root-packages/commit/e85a7cf7980ff06a0a30526811fcf6c669b7ad4f), but when I try to attach to a process with something like:

```python
#!/data/data/com.termux/files/usr/bin/python3
import time

import frida

device = frida.get_device("local")
pid = device.spawn(["com.termux.api"])
```

I get

```
# ./loader.py
Traceback (most recent call last):
  File "loader.py", line 7, in <module>
    pid = device.spawn(["com.termux.app"])
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/frida/core.py", line 140, in spawn
    return self._impl.spawn(program, argv, envp, env, cwd, stdio, aux_options)
frida.NotSupportedError: unable to access zygote64 while preparing for app launch; try disabling Magisk Hide in case it is active
```

If I get the PID with `frida-ps` and try to attach with 

```python
#!/data/data/com.termux/files/usr/bin/python3
import time

import frida

device = frida.get_device("local")
pid=8231
device.resume(pid)
```

I get 

```
Traceback (most recent call last):
  File "loader.py", line 9, in <module>
    device.resume(pid)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/frida/core.py", line 148, in resume
    self._impl.resume(self._pid_of(target))
frida.NotSupportedError: unable to handle 32-bit processes due to build configuration
```

But I am fairly sure that all libraries/binaries are 64bit (at least the binary I want to attach to and the frida lobraries). @oleavr do you have any suggestion about what might be going on?

**Comment by oleavr** [comment]
@Grimler91 Is that process running as root? Also, you will need to do what `frida-server` currently does when running on Android – inserting some rules into the running kernel's SELinux policy:
https://github.com/frida/frida-core/blob/9e8f89f886a8759bbb9737a8819b1dec53e44b5a/server/server-glue.c#L72

**Comment by Grimler91** [comment]
> Is that process running as root?

I tried to: attaching to a none-root process in termux, a root process in termux, and a process from a different app but it gives the same result, `unable to handle 32-bit processes due to build configuration`. The loader.py script is run as root. 

> Also, you will need to do what `frida-server` currently does when running on Android – inserting some rules into the running kernel's SELinux policy

Alright, and that has to be done by frida-python (i.e. I need to patch _frida.c from frida-python to do this)? (I have tried having frida-server running, as root, at the same time as I play around with frida-python but it doesn't seem to do a difference). 

I should probably mention that I am testing on a lineageos 17.1 (android 10) arm64 phone, selinux is set to permissive.

**Comment by shadowslasher410** [comment]
@Grimler91 Don't know if you know this but just because Magisk Hide isn't enabled for any apps doesn't necessarily mean that its completely off - which it needs to be (I had problems with this too, before I figured it out). Double check by going to the Magisk Manager, into settings, and make sure Magisk Hide is set to Off.

**Comment by Grimler91** [comment]
@shadowslasher410 Thanks, I did not know that. After turning off magisk hide for real I get the `unable to handle 32-bit processes due to build configuration` error when doing `device.spawn()` as well. 

I also tried patching the frida-python library to do `frida_selinux_apply_policy_patch ();` at the beginning of `PyDeviceManager_get_device_matching`, but it has not helped.

The error originates from here: https://github.com/frida/frida-core/blob/77ffc319827cd2f342ee581bd7d86242d27cc6de/src/linux/frida-helper-process.vala#L172, I'll try to understand why it happens.

I have uploaded the aarch64 debs here if you want to test it: https://grimler.se/frida-server_12.8.13_aarch64.deb, https://grimler.se/frida-python_12.8.13_aarch64.deb, https://grimler.se/frida-tools_12.8.13_aarch64.deb.

**Comment by oleavr** [comment]
@Grimler91 Normally that error means your Frida build is 64-bit only, so it doesn't have a `frida-agent.so` (and `frida-helper`) for 32-bit processes. This is typically because it was built using one of the `-thin` targets. But yeah you definitely found the root cause there 👍

(You can ignore `frida_selinux_apply_policy_patch ()` if you're running with SELinux in permissive mode.)

**Comment by Grimler91** [comment]
@oleavr Changing so that it builds with frida-android-* instead of frida_thin-android-* fixed it indeed, thanks for the help!

I have added frida-python and frida-tools to the termux repository now, some tests on aarch64 works fine. I did not add the `frida_selinux_apply_policy_patch ()` patch in this first commit as I want to make a more proper patch than in my previous hack test. 
When I test frida-python on arm (android 7.1, selinux enforcing) I get a segmentation fault and the device reboots, maybe due to it not running `frida_selinux_apply_policy_patch ()`. So, @shadowslasher410, beware that it might cause device reboots at the moment
