### ISSUE TITLE
Failed to spawn: unable to find application with identifier

### ISSUE THREAD

**Issue by v3rybad** [frida/frida#1205]
```
macedonians% frida -U -l /home/kira/Desktop/frida.js --no-paus -f com.twitter.com
     ____
    / _  |   Frida 12.2.27 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at http://www.frida.re/docs/home/
Failed to spawn: unable to find application with identifier 'com.twitter.com'
macedonians% 
```

i have even downgraded frida to 12.2.27.
when i use frida-ps it is showing but, it is not showing after running frida
```
macedonians% frida-ps -U | grep -i "twitter"
3755  com.twitter.android
macedonians% 
```

**Comment by oleavr** [comment]
You might have more than one USB device plugged in. Check with `frida-ls-devices`, and specify `-D <device-id>` instead of `-U` to pick a specific one. Use `frida-ps -D <id> -ai` to list installed apps and make sure `com.twitter.com` is in that list. Also make sure you're running the latest Frida while doing this. (Many Android-related fixes happened in recent releases.)

**Comment by xehpuk** [comment]
`com.twitter.com` != `com.twitter.android`
