### ISSUE TITLE
early tracing for processes (Android)

### ISSUE THREAD

**Issue by dweinstein** [frida/frida#13]
What's the recommended way to perform early tracing with frida, on Android in particular. I'd like to make sure that I am tracing the functions during app startup. Currently it seems the required workflow is to hook an already running process. Is there a plan in place to support it? if there is I might be able to take a stab at implementing it.

**Comment by oleavr** [comment]
Frida provides the `spawn()`/`resume(pid)` API, where the former creates the process with the main thread suspended, and the latter resumes the main thread. In between these two calls you're meant to `attach(pid)` as you'd otherwise do, trace any functions of interest, and then call `resume(pid)`.

On Android, however, this isn't very useful as zygote simply forks whenever an app is to be spawned. This is not currently supported by Frida, but definitely something that should be supported, so it would be awesome if you could take a stab at implementing it!

**Comment by oleavr** [comment]
Any luck? By the way, the `spawn()` implementation should work much better on Linux and Android now.

**Comment by dweinstein** [comment]
haven't had the time yet :-(

**Comment by oleavr** [comment]
Me neither; time flies! :/ I had a quick look at the Android internals by the way, and it looks like it's possible to spawn an app by invoking `/system/bin/app_process` directly. This means it's possible to do this with Frida already, although probably not straight-forward. Perhaps an elegant solution would be that our `spawn()` implementation checks if argv[0] starts with a '/', and if it doesn't, it assumes a package name, like `com.android.browser`, and does the necessary set-up for you. But anyway, a good first step is probably trying to do this by hand to figure out what's necessary, and then automate it as a second step.

**Comment by dweinstein** [comment]
I started investigating how the Android Studio IDE handles suspending processes for debugging with JDWP...and with a hook to [`android.os.Process.class.start`](http://androidxref.com/4.4.4_r1/xref/frameworks/base/core/java/android/os/Process.java#388) which also gives you a good time to switch the value of `debugFlags` i.e., `args[5] = ((Integer) args[5] | 0x1);` which will have the processes start with debugging enabled each time. When debugging with the IDE apps can be started suspended as well which might be useful for frida... still trying to figure out how this works exactly but based on [`this`](http://androidxref.com/4.4.4_r1/xref/frameworks/base/core/jni/AndroidRuntime.cpp#636) and assuming we're still talking about Dalvik runtime then we might be able to adjust the args and include the `suspend=y` option to out advantage.

Honestly I was successful with using xposed to hook `android.os.Process.start` but I haven't figured out how precisely to do this yet with Frida :-)

**Comment by oleavr** [comment]
Aha, cool! Yep, figuring out how the IDE starts app suspended could definitely prove very useful for us.

Regarding xposed, the reason this works is that their payload is part of any new process spawned, whereas if you use Frida to inject into Zygote it will stay behind when it calls `fork()` to become the app to be spawned. (Though technically Frida's code will be part of the newly forked child, but no threads survive the fork except the thread that called `fork()`, so any hooked functions will call into Frida code in an undefined state; e.g. a thread may have held a lock at the time the `fork()` happened, and trying to take that lock will leave future lock-acquirers waiting forever.) So that's the disadvantage of our current dynamic approach, but well, there must be an elegant solution hiding in there somewhere. :-)

**Comment by shuffle2** [comment]
I was just looking to do a similar thing and came here to say: it would be nice if frida-trace (and other bundled tools) allowed starting the process as well.  
Then I realized it actually is supported, it just apparently needs an absolute path to the file to execute. Would be nice to state that somewhere...

**Comment by oleavr** [comment]
This is finally implemented in the latest release, 4.5.1. It is now possible to:
- `spawn(["com.android.browser"])` with the package name, just like on iOS.
- `enable_spawn_gating()` and listen to the `spawned` signal in order to do early instrumentation of services and other processes spawned implicitly when launching the app, or any other time for that matter. This is also supported on iOS.

Note that the ART hooking isn't working well due to:
https://github.com/frida/frida-gum/issues/105
https://github.com/frida/frida-gum/issues/106
For now I would recommend sticking with a 4.4 emulator image, or a 4.x device.

**Comment by GHXST01** [comment]
@dweinstein Hey! I know this is a while ago, but have you had progress hooking `android.os.Process.start` now we are able to spawn apps? I would still like force-able debug to be a thing and would very much like to be able to submit a PR for it if I am able to do so.

**Comment by rain6851** [comment]
@oleavr ,if i want to start a new process with some arguments using spawn, it fail.

**Comment by KaelLuo** [comment]
For anyone comes here and still struggle for early Android tracing. 
Currently frida already support early tracing but when you trace multi functions, frida still not early enough...
My solution is stuck app and resume it after frida ready to trace. so..
First, run
`adb shell am set-debug-app -w your_package_name`
Then start your app and frida as normal, you'll find frida could attach to process normally, and app is showing "waiting for debugger" and paused.
Then you just need resume the app, meaning attach debugger 
```
# To get pid of your application
adb shell pidof your_package_name
# forward xxxx port to your pid, xxxx could be any number you like
adb forward tcp:xxxx jdwp:$pid
# attach debugger and your app will resume
jdb -attach localhost:xxxx
```
**Please remember, do not open Android Studio when you run those command**
