### ISSUE TITLE
[Question] Regarding frida and emulator with libcocos2dcpp.so

### ISSUE THREAD

**Issue by Nightshades1** [frida/frida#1333]
Hello, i'm doing evil stuff on a game that use cocos2d-x (on emulator) and i was wondering what is the reason that frida cannot find libcocos2dcpp.so in the enumerated modules.

I tested on Memu both android x64 or x86 version of android and it still doesn't find anything, though, i can see the module loaded with Interceptor.attach on dlopen, is that because the emulator translate the arm instruction or something (with the help of libhoudini the arm translation layer for x86/x64).

This is a bit annoying because my galaxy tab s6 isn't rooted and i don't want to, well i do use frida-gadget no issue on physical device, but it would be way easier if it was also working on emulator.

I use Typescript with visual studio code.

**Comment by oleavr** [comment]
It's because the code being emulated is its own world so it even has its own dynamic linker, and you're loading Gadget into the native world outside it – where the native dynamic linker has no knowledge of the emulated one. As a workaround you could include an ARM Gadget and convince the emulated portion to load it as if it was any other ARM library.

I plan on adding native support for this in Frida at some point, by shipping an ARM frida-agent with the x86 frida-server, and make the x86 agent aware of Houdini so it can switch over to the ARM agent if it detects that the process is using emulation.

**Comment by Nightshades1** [comment]
> As a workaround you could include an ARM Gadget and convince the emulated portion to load it as if it was any other ARM library.
:ok_hand: :100:
