### ISSUE TITLE
Can't hook interface implementations in Android Java

### ISSUE THREAD

**Issue by natashenka** [frida/frida#1395]
I've been looking at Android applications, and I've had many problems like the following.

In the application, there is the following class:

```
.class public final Lcom/viber/voip/phone/ViberRTCCall;
.super Ljava/lang/Object;
.source "SourceFile"

# interfaces
.implements Lcom/viber/voip/phone/RTCCall;
```

It implements the following abstract method.

`.method public startCall(I)V`

I've tried hooking it with the following code in frida, but it doesn't work.

```
 var viber = Java.use("com.viber.voip.phone.ViberRTCCall");
   var startsend = viber.startCall;
   
     startsend.implementation = function (a) {
     	console.log("start send");
     	startsend.call(this, a);
     
     }
```
I can see that the Java method startCall gets called by adding stack traces to methods it calls, but the hook code never gets called. Not sure if this is a problem with Frida, or if my script is incorrect. Thanks!

**Comment by oleavr** [comment]
This is usually caused by optimizations, where some call sites may be optimized. Try prefacing your script with:

```js
Java.performNow(function () {
  Java.deoptimizeEverything();
});
```

Or if you're using `frida-trace -j` for tracing Java methods (recent feature), you can put the above snippet in e.g. `init.js` and add `-S init.js`.

Also worth noting that I've seen this kind of issue on Android 5 and 6, but on newer versions the above has always solved the issue for me. (So haven't bothered investigating what's up on 5 and 6.)

**Comment by natashenka** [comment]
That works, thanks so much!

**Comment by 0x1shyboy1** [comment]
thanks oleavr so much!

**Comment by binbon2d** [comment]
`Java.deoptimizeEverything();`
```
 TypeError: cannot read property 'address' of undefined
    at <anonymous> (frida/node_modules/frida-java-bridge/lib/android.js:1536)
```
On Frida 16.1.4
