### ISSUE TITLE
allocUtf8String can not work sometimes

### ISSUE THREAD

**Issue by BurningTeng** [frida/frida#1550]
When I write code as below, It can works well and readUtf8String() can return "Hello world".
```  
        var openFunc = Module.getExportByName("libc.so", 'open');
          Interceptor.attach(openFunc, {
            onEnter: function (args) {
                const bu = args[0];
                var buf = Memory.allocUtf8String("Hello world");
                this.buf = buf;
                args[0] = this.buf;
                console.log("Burning"+args[0].readUtf8String());
                args[0] = bu;
            },
            onLeave: function (retval) {
              //console.log("retval "+retval.toString());
            }
          });`
```
But when I write code as below, readUtf8String() can not return "Hello world".
args[0] = Memory.allocUtf8String("Hello world");
```
          var openFunc = Module.getExportByName("libc.so", 'open');
          console.log("burning"+openFunc);
          Interceptor.attach(openFunc, {
            onEnter: function (args) {
                const bu = args[0];
                args[0] = Memory.allocUtf8String("Hello world");
                console.log("Burning"+args[0].readUtf8String());
                args[0] = bu;
            },
            onLeave: function (retval) {
              //console.log("retval "+retval.toString());
            }
          });
```
![burning](https://user-images.githubusercontent.com/20567891/100830803-74442700-349f-11eb-810a-ce191438e22d.png)

**Comment by oleavr** [comment]
It's because assigning to `args[x]` doesn't store the JS value there as it's not actually a JS array (though it pretends to be one), it only takes its pointer value and writes that to the register or memory that will be passed to the function. Then the JS value gets garbage collected, which frees the memory belonging to the underlying string.

This is indeed not super-intuitive, but you should make sure that you keep such allocations alive for the duration of the function call (or however long the code the pointer is passed to expects to be able to use the pointer).

See https://frida.re/docs/best-practices/ for more details.
