### ISSUE TITLE
Can I hook a function by its address in android?

### ISSUE THREAD

**Issue by wejdan** [frida/frida#160]
I want to hook to stripped .so file in android application so I do not have the name of the functions

first I get the base address of the module
```
src="""
send(Module.findBaseAddress("libctr-jni.so"));
""" 
```
then I add the address to the address of the function that I want to hook

```
src="""
Interceptor.attach(ptr(0xaf13b01c), {
    onEnter: function(args) {

    },
    onLeave:function(retval){

       retval.replace(0x9);

    }
});
""" 
```

however the app crush immediately once I run the script

I do not know if I am doing something wrong or the app is protected somehow

**Comment by oleavr** [comment]
Hi,

Is this an ARM or Thumb function? If it's a Thumb function you will have to set the lower bit (i.e. `0xaf13b01d` in your example), as specified in the [documentation](http://www.frida.re/docs/javascript-api/#interceptor). You should also pass the argument to `ptr()` as a string, as you otherwise could run into issues with 64-bit targets where a JavaScript Number cannot represent the full pointer value.

Cheers

**Comment by wejdan** [comment]
how do I pass the arguments? for example if the function take two integers

**Comment by oleavr** [comment]
Sorry I'm not sure I understand your question. Your example is hooking the function, so you get callbacks before and after it is called. There is then no need to call the original function, because Frida is doing it for you. However if you used `Interceptor.replace()` you would have to call it yourself if you still want the original implementation to get called.

**Comment by wejdan** [comment]
Thank you I did set the lower bit to 1 and now it work :)

**Comment by oleavr** [comment]
Glad to hear! Happy hacking! :)
