### ISSUE TITLE
NativeCallback not working properly since v14.x.x

### ISSUE THREAD

**Issue by Manny684** [frida/frida#1638]
Since Frida went to Version 14, I am having issues with setting Callbacks. See the following example:

Say we target [this very simple openssl TLS Server implementation](https://wiki.openssl.org/index.php/Simple_TLS_Server). We want to extract the TLS keys, so we try to use `SSL_CTX_set_keylog_callback` to set a callback function which receives the logged Keys. Here is a minimalistic script for injection:

```javascript
var SSL_CTX_set_keylog_callback = new NativeFunction(Module.findExportByName("libssl.so", "SSL_CTX_set_keylog_callback"), "void", ["pointer", "pointer"]);

Interceptor.attach(Module.findExportByName("libssl.so", "SSL_new"),
    {
        onEnter: function (args) {
            var keylog_callback = new NativeCallback(function (ctxPtr, linePtr) {
                console.log(linePtr.readCString());
            }, "void", ["pointer", "pointer"])
            SSL_CTX_set_keylog_callback(args[0], keylog_callback);
        }

    })
```

This works like a charm in version 12.11.18, but since 14.0.0 and ever since the targeted server crashes after the initial SSL Handshake, and nothing is printed. Setting the callback via `SSL_CTX_set_keylog_callback` should work, as I have compared the addresses of `keylog_callback` by printing them in the script and in the target program. Does anyone have an idea why the programm crashes, or is this maybe a bug in frida v14+?

**Comment by oleavr** [comment]
This only worked by luck previously – actually IIRC we had a bug where `NativeCallback` objects were kept alive by mistake and thus ended up leaking. The issue here is that `keylog_callback` isn't referenced by anything at the end of `onEnter`, which means it may get garbage-collected, and that means the pointer you gave to `libssl.so` becomes invalid or ends up pointing to something else. The fix is simple though: declare a variable in the top-level scope. E.g.:

```js
const setKeylogCallback = new NativeFunction(Module.findExportByName('libssl.so', 'SSL_CTX_set_keylog_callback'), 'void', ['pointer', 'pointer']);

const keylogCallback = new NativeCallback((ctxPtr, linePtr) => {
    console.log(linePtr.readCString());
}, 'void', ['pointer', 'pointer']);

Interceptor.attach(Module.getExportByName('libssl.so', 'SSL_new'), {
  onEnter(args) {
    setKeylogCallback(args[0], keylogCallback);
  }
});
```

(Also updated to use modern syntax and idiomatic naming conventions.)

Cheers!
