### ISSUE TITLE
unc0ver 6.0.0 / iOS 14 support?

### ISSUE THREAD

**Issue by Manouchehri** [frida/frida#1649]
I've installed Frida for A12+ devices (14.2.13), but it doesn't seem to work with unc0ver 6.0.0 on iOS 14.2.

```
iphone11:~ root# /usr/sbin/frida-server 
-sh: /usr/sbin/frida-server: Bad CPU type in executable
iphone11:~ root# file /usr/sbin/frida-server
/usr/sbin/frida-server: Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE>
iphone11:~ root# sw_vers 
ProductName:    iPhone OS
ProductVersion: 14.2
BuildVersion:   18B92
iphone11:~ root# uname -a
Darwin iphone11 20.1.0 Darwin Kernel Version 20.1.0: Fri Oct 30 00:34:17 PDT 2020; root:xnu-7195.42.3~1/RELEASE_ARM64_T8030 iPhone12,1 arm64 N104AP Darwin
```

I've also checked off "Export TFP0" in the settings, but I don't think it actually does anything on iOS 14. I tried another tool that tries to use tfp0 and it fails.

```
iphone11:~ root# nvnonce 
Attempting to read boot-nonce variable without patches
(null)
Failed to get boot-nonce without patches
Init tfp0
kernel_task is not valid
failed to init tfpzero
load offsets
dimentio attempt
PROC_P_PID_OFF: 68
TASK_ITK_REGISTERED_OFF: 308
arm_pgshift: 14
tfp0: 0x0
dimentio: could not get the boot nonce os string address
unlocking nvram
Failed to unlock nvram
Failed to read generator
```

**Comment by brandonkovacs** [comment]
I experience the same problem as you when running `frida-server` on my rooted iOS Device.

I believe this issue is related to #1647.

When running `frida-ps -U` on my Macbook, I also receive the following error:

`Failed to enumerate processes: this feature requires an iOS Developer Disk Image to be mounted; run Xcode briefly or use ideviceimagemounter to mount one manually`

Running iOS 14.0 on an iPhone XS.

**Comment by Manouchehri** [comment]
My bad, this is totally a duplicate of #1647 then. Not sure how I missed it, thanks!
