### ISSUE TITLE
error: unable to intercept function at 0xb74facfc; please file a bug

### ISSUE THREAD

**Issue by mxy19980428** [frida/frida#1670]
When I use the FIRDA 14.2.13 version, the address of hook 0x203acfc tells me: error: unable to intercept function at 0xb74facfc; please file a bug. Is it because the address is too large that it can't work? Is there a solution?

**Comment by mxy19980428** [comment]
.text:0203ACF8                 ADDS            R1, R0, R2
.text:0203ACFA                 ADD             R0, SP, #0x108+var_58
.text:0203ACFC                 BL              sub_2046542

When I hook the first address: 0203acf8, there is no problem. The second and third address are not OK

**Comment by mxy19980428** [comment]
![image](https://user-images.githubusercontent.com/34773306/112126294-4413c600-8bff-11eb-95d7-d8303cf38b08.png)

**Comment by oleavr** [comment]
This happens because there's not enough space for the inline hook, as Interceptor refuses to overwrite past that BL as a thread may already have executed that BL but not yet returned, and we don't want it returning to something unexpected once it does return. You can always combine Interceptor with Stalker, or craft a hook manually using `Memory.patchCode()`.

Cheers!
