### ISSUE TITLE
Intercept address within intercept.attach call

### ISSUE THREAD

**Issue by jabbink** [frida/frida#173]
Hi, I encountered a piece of software that unpacks itself piece by piece (every tiny piece unpacks a new piece and jumps into it).

I thought I can put a simple script together to automatically intercept the beginning of each of these little pieces and dump some register information, unfortunately intercepting a new address from within a `Interceptor.attach` call fails.

`Error: unable to intercept function at 0x7fd6da74b036; please file a bug`

The eventual jump to the next unpacked piece:

```
Instruction.parse(ptr('0x7fd6da74b036'))
{
    "address": "0x7fd6da74b036",
    "mnemonic": "jmp",
    "next": "0x7fd6da74b038",
    "opStr": "0x7fd6da74b065",
    "size": 2
}
```

After the code has been unpacked, this is the address referenced in the jump.

```
Instruction.parse(ptr('0x7fd6da74b065'))
{
    "address": "0x7fd6da74b065",
    "mnemonic": "lea",
    "next": "0x7fd6da74b069",
    "opStr": "esi, dword ptr [rsi]",
    "size": 4
}
```

My code: 

```
    Interceptor.attach(ptr('0x400875'),
      function(args) {
        var baseAddress = ptr(args[0])

        Interceptor.attach(
          ptr(baseAddress.add(0x36)), function() {
              console.log('unpacked layer');
              // do more stuff
          }
        )
      }
    );
```

(I verified (with gdb) that the actual address is correct, also the `lea esi, dword ptr [rsi]` on the address of the unpacked block is what I expect)

**Comment by oleavr** [comment]
@jabbink That should indeed work. The problem is that Interceptor may need to overwrite more than just one instruction, and sometimes there just isn't room to overwrite more than one, e.g. end of the basic block comes next. But, we do have logic that tries to find code caves so it can get away with shorter jumps, so we don't have to overwrite that much. This logic is however [only implemented in the arm and arm64 Interceptor backends](https://github.com/frida/frida-gum/search?utf8=%E2%9C%93&q=gum_code_allocator_alloc_deflector&type=Code), so we still need to implement this in the [x86 backend](https://github.com/frida/frida-gum/blob/master/gum/backend-x86/guminterceptor-x86.c). Let me know if you're interested in exploring this.

**Comment by jabbink** [comment]
Currently on mobile so can't look into it. I was suspecting this and actually made room behind the 036 address (put about 10-15 not instructions there hoping it would be enough) but it didn't work. Will possibly look into this later today.

**Comment by oleavr** [comment]
Should be improved in latest Frida 9.x.
