### ISSUE TITLE
Using frida on Objective-C of calling function CGContextDrawImage that takes a struct param

### ISSUE THREAD

**Issue by joshuachenn** [frida/frida#1973]
I'm calling CGContextDrawImage function using code shows below:
```javascript
var CGContextDrawImagePtr = Module.findExportByName(null, 'CGContextDrawImage')
var CGContextDrawImage = new NativeFunction(CGContextDrawImagePtr, 'void', ['pointer', 'pointer', 'pointer'])

var rect = Memory.alloc(32);
rect.writeByteArray([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x7E, 0x40, 0, 0, 0, 0, 0, 0, 0x84, 0x40]);
console.log('rect:', hexdump(rect, {length:32}))
CGContextDrawImage(context, rect, imageRef)
```

I know that it is wrong to pass structure parameters to CGContextDrawImage in this way, but how can I pass the CGRect structure parameters to such a function correctly?

declare of `CGContextDrawImage` function shows below:
```objective-c
CG_EXTERN void CGContextDrawImage(CGContextRef cg_nullable c, CGRect rect,
  CGImageRef cg_nullable image)
  CG_AVAILABLE_STARTING(10.0, 2.0);
```
By the way, it can be seen through disassembly that the CGRect parameter passed to the function is actually used to fetch the value through the d0, d1, d2, and d3 registers.

**Comment by oleavr** [comment]
Not sure if this is documented very well, but `NativeFunction` supports this, and all the heavy lifting is handled by libffi.

Instead of `'pointer'`, you want something like: `[['double', 'double'], ['double', 'double']]`. Here we're saying our struct (`CGRect`) has two fields, each a struct; one `CGPoint` and one `CGSize`. Both of them have two fields, each a `CGFloat`. (Which is a `double` on all OSes except watchOS, where it is a `float`.) Then to pass this argument, do `[[x, y], [w, h]]`.

Cheers!

**Comment by joshuachenn** [comment]
Nice! It works! Thanks a lot!
