### ISSUE TITLE
How filter call native in onEnter ?

### ISSUE THREAD

**Issue by maxben14** [frida/frida#2092]
I use frida-trace and I want to determine inside the OnEnter method where the call to this intercepted function came from.
I have a function A that is called from 1 and 2 libraries, I want the interception to catch calls from 1 library and not display calls to function A from 2 libraries. How to do it ?
How can I get a stack trace inside OnEnter and find out the name of the function from which my function A was called?

**Comment by oleavr** [comment]
If you only need the direct caller you can use `this.returnAddress`. You could then have a `ModuleMap` instance that's filtered to only contain the ones you care about, so the lookup will be quick. If you want a full backtrace, however, do `Thread.backtrace(this.context)`. This returns an arrray of `NativePointer` values, and since it's an array you can do `.map(DebugSymbol.fromAddress).join('\n\t')` to symbolicate it and join the frames by newline + tab.
