### ISSUE TITLE
Array has no length?

### ISSUE THREAD

**Issue by krokofant** [frida/frida#221]
```js
{u'columnNumber': 1,
u'description': u'Error: invalid index',
u'fileName': u'input',
u'lineNumber': 24,
u'type': u'error',
u'stack': u'Error: invalid index\n    at input:24\n    at call (native)\n    at invokeCallback (tracer.js:33)\n    at tracer.js:39'}
```

```js
    onEnter: function (log, args, state) {
        log(args.length)
    },
```
Just trying to log the length of the array (args) of NativePointer on an onEnter method. Also tried with Array.isArray(args) which says it's not really an array. What am I missing?

**Comment by oleavr** [comment]
This is by design, `Interceptor` knows nothing of the function you're hooking. (And this kind of metadata is not available at runtime unless you have debug symbols.) The `args` object just behaves like a virtual array with an infinite number of elements, and if you read arguments out of bounds you will be reading garbage.

It doesn't actually make any assumptions that you're asking it to hook a function – you can specify a callback instead of the `{ onEnter... }` object, and it will allow you to add a probe in the middle of a function.

This is intentional as requiring `Interceptor` to know the exact signature means it will be very hard to use it for reverse-engineering. Currently you can enumerate all the exported functions of a library, say, and hook all of them, without knowing anything about each function's number of arguments or their types, the return type, etc. But if you do know this you can use `Interceptor.replace()` and give it a `NativeCallback` with the exact signature as the replacement, in which case you can use `arguments.length` to know how many arguments are there. (But you already knew that as you had to create the `NativeCallback` in the first place.)
