### ISSUE TITLE
Frida 16.0.2 Failed to spawn: need Gadget to attach on jailed Android

### ISSUE THREAD

**Issue by makovez** [frida/frida#2326]
I have a One Plus 9 with lineage OS, rooted with magisk installed.

I installed frida last version and frida-tools with pip3
**frida 16.0.2
frida-tools-12.0.2**

Then i installed **frida-server-16.0.2-android-arm64** on my device which is arm64. I run `chmod 755` and run frida-server as root from adb.

All seems good and **It is NOT giving me any error**. When i run `frida-ps -U` i can see the frida-server process.
`3525  frida-server`

When i try to issue this command i get:
```
C:\> frida-trace -U -f open com.android.settings
Failed to spawn: need Gadget to attach on jailed Android; its default location is: C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\AC\INetCache\frida\gadget-android-arm64.so
```

Same when i try to run objection with:
```
C:\> objection --gadget com.android.settings explore
Using USB device `LE2123`
Unable to connect to the frida server: need Gadget to attach on jailed Android; its default location is: C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\AC\INetCache\frida\gadget-android-arm64.so
```

I have always used frida with another device without any problem...
Do you think is a problem related to the android device or the is the pc missing some packages? I don't get why it mentions this `C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\AC\INetCache\frida\gadget-android-arm64.so` which is a package in the pc.., shouldn't it be in the android phone?

**Comment by oleavr** [comment]
Hi,

The issue is that the host-side Frida is 15.x, whereas the device-side is 16.x. This will be resolved once Objection moves to Frida 16. There's a pull-request for it that you can use as a stop-gap solution: https://github.com/sensepost/objection/pull/579
/cc @leonjza

Cheers!

**Comment by makovez** [comment]
Thanks for your quick answer!


> The issue is that the host-side Frida is 15.x

What do you mean by host-side ? I have frida 16.0.2 installed in my pc 

I thought that if I downgrade everything to 15.x, it would work, but no.

I have tried to downgrade to 15.2.2 both frida (also frida-tools) in my pc and frida-server in the device-side. But I got the same problem. 

I have not touched objection which was always on version 1.11.0

**Comment by oleavr** [comment]
The issue is that Objection has its own copy of Frida. (Which may or may not be the same as used by frida-tools.)

**Comment by makovez** [comment]
> There's a pull-request for it that you can use as a stop-gap solution: https://github.com/sensepost/objection/pull/579

I have tried to use this pull request and install objection from it. But nothing has changed, I get same problem. Are you sure the issue is about that?

**Comment by makovez** [comment]
The problem is related with the interaction of AF WALL and the package com.android.shell.

I am currently using afwall to pass all the traffic through tor. When allowing com.android.shell to don't pass through tor, then that error disappear.

However, I have no idea of what com.android.shell does and how it can cause the issue in Frida. 

If anyone has any idea of the possible cause of this let me know.

**Comment by leonjza** [comment]
> The issue is that Objection has its own copy of Frida. (Which may or may not be the same as used by frida-tools.)

Not 100% sure I'm following this one, but we use binary releases of Frida from Github. If @makovez does `pip install -U frida frida-tools`, objection should work fine. We require at least v15 with no upper limit to the version.

**Comment by makovez** [comment]
> > The issue is that Objection has its own copy of Frida. (Which may or may not be the same as used by frida-tools.)
> 
> Not 100% sure I'm following this one, but we use binary releases of Frida from Github. If @makovez does `pip install -U frida frida-tools`, objection should work fine. We require at least v15 with no upper limit to the version.

The problem is not related with objection for sure as it is running fine in another device. 

As mentioned in my last comment, the problem is related to the interaction of frida-server (i guess) and the package com.android.shell with AF wall active.

**Comment by z0xyz** [comment]
> objection should work fine. We require at least v15 with no upper limit to the version.

When it comes to versioning, that did work. However, the same error arises when the patched app doesn't hang -to be resumed with `objection explore`-, and opens right away. Invoking objection at this case -or without any app running actually- raises the same error.

**Comment by subvert0r** [comment]
Any news...? Still a problem...

**Comment by nashor1** [comment]
得先在电脑上用adb启动你手机的frida-server

**Comment by salahxgamer** [comment]
I had the same problem recently, it worked fine before, it turned out i was using a socks proxy which messed around with the communication, if you have been using a proxy try to limit it to the desired application (something like ProxyDroid does)

**Comment by Said-ai** [comment]
before running objection you have to run frida on your emulator.
`adb shell
su
cd /data/local/tmp/
./frida-server`

that works for me

**Comment by thewindgod9** [comment]
> > > The issue is that Objection has its own copy of Frida. (Which may or may not be the same as used by frida-tools.)
> > 
> > 
> > Not 100% sure I'm following this one, but we use binary releases of Frida from Github. If @makovez does `pip install -U frida frida-tools`, objection should work fine. We require at least v15 with no upper limit to the version.
> 
> The problem is not related with objection for sure as it is running fine in another device.
> 
> As mentioned in my last comment, the problem is related to the interaction of frida-server (i guess) and the package com.android.shell with AF wall active.

This is the perfect solution.

**Comment by Rayan-web** [comment]
the same problem any help?

**Comment by DarkSkull91** [comment]
For me these exact commands of the official documentation works:
```
$ adb root # might be required
$ adb push frida-server /data/local/tmp/
$ adb shell "chmod 755 /data/local/tmp/frida-server"
$ adb shell "/data/local/tmp/frida-server &"
```
*Note that you give the last command from the phone**, in other words you have firstly to launch `adb shell` command and then issue this command `/data/local/tmp/frida-server & `. In this way I am using the last version of `frida `and `frida-tools` without issue, both on my rooted phone and on android emulators.

**Comment by karthi-the-hacker** [comment]
I faced the same issue, 'Failed to spawn: need Gadget to attach on jailed Android.'

I tried manually adding 'gadget-android-arm64.so' into the cache directory, but it didn't work.

Then, I removed the 'gadget-android-arm64.so' file that I had manually added. After that, I restarted my Genymotion emulator and downloaded the Frida Server, ensuring it was the same version as my Frida client.

My setup:

- Frida client version 16.1.4
- Frida Server version 16.1.4 (x86) for my Windows host machine emulator
- Frida Server version 16.1.4 (arm64) for my Mac (M1) host machine emulator

Next, I pushed the Frida Server to the emulator using 'adb push frida-server /data/local/tmp/' and added the necessary permissions to 'frida-server' using the 'chmod 755 frida-server' command.

Now, the real challenge began. Instead of running 'frida-server' as 'su' (super user)eg : '**su frida-server &**' , I tried running it as '**./frida-server &**' or '**./frida-server**.' Both options worked for me. The issue seemed to be related to running 'frida-server' as a super user."

I made some punctuation and phrasing adjustments to improve clarity and readability.

**Comment by denes096** [comment]
> For me these exact commands of the official documentation works:
> 
> ```
> $ adb root # might be required
> $ adb push frida-server /data/local/tmp/
> $ adb shell "chmod 755 /data/local/tmp/frida-server"
> $ adb shell "/data/local/tmp/frida-server &"
> ```
> 
> _Note that you give the last command from the phone_*, in other words you have firstly to launch `adb shell` command and then issue this command `/data/local/tmp/frida-server & `. In this way I am using the last version of `frida `and `frida-tools` without issue, both on my rooted phone and on android emulators.

That was the solution for me! Frida server was not running on the phone
16.1.4

**Comment by Hurshid88** [comment]
pip installed `frida 16.0.1` version
`Frida-Server 16.1.8` version on my android device

Frida server on my android device is running
`frida -U -f <app name> -l C:\Users\acer\Desktop\fridascript.js --paus`

Failed to spawn: dlopen failed: library "/proc/self/fd/403" not found
Server is running on my android device

Please help

**Comment by xbr01** [comment]
running frida server on another terminal(inside /data/local/tmp/) solved the issue for me

**Comment by victorwaldron** [comment]
Hello, I am having this problem when running frida -U -l root_bypass.js -f com.example_test, what I do not understand is that frida-server is version 14.2.17 x86 architecture and I am also using the frida-gadget x86 and I see Frida is trying to locate this file gadget-android-arm64.so,
  ____
    / _  |   Frida 16.2.1 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to A10 (id=192.168.56.106:5555)
Failed to spawn: need Gadget to attach on jailed Android; its default location is: /home/user/.cache/frida/gadget-android-arm64.so

then in that direction, taking into account that the architecture of the android device is x86, I have copied frida-gadget in that direction and it gives me the same error, since it continues pointing to gadget-android-arm64.so, then I have renamed the x86 gadget file to the one indicated, but when I run it again I have this result ____
     /_ | Frida 16.2.1 - A world-class dynamic instrumentation toolkit
    | (_| |
     > _ | Commands:
    /_/ |_| help -> Displays the help system
    . . . . object? -> Display information about 'object'
    . . . . exit/quit -> Exit
    . . . .
    . . . . More info at https://frida.re/docs/home/
    . . . .
    . . . . Connected to A10 (id=192.168.102.106:5555)
Failed to attach: connection closed

This opens the app, but it still does not do the bypass, since the device indicates that the device is disabled, because it is rooted

**Comment by SarkastikMaster** [comment]
![issue](https://github.com/frida/frida/assets/28308872/818c6901-e679-40c7-a89f-d3e0e272ec95)
I have approached an issue with spawning into a gadget and receiving my device info. What should I do?

**Comment by victorwaldron** [comment]
For this to work, the frida-gadget-16.2.1.. file must also be copied into the device folder /data/local/tmp along with the frida-server-16.2.1.. file with the corresponding permissions for its execution. , and taking into account what I placed previously that frida looks for the arvhico gadget in the address for example: /home/user/.cache/frida/gadget-android-arm64.so
note: if the frida folder is not inside .cache, you must create it

**Comment by SarkastikMaster** [comment]
What are installation steps followed by pushing it into the device?

**Comment by victorwaldron** [comment]
https://www.hackingarticles.in/android-penetration-testing-frida/

**Comment by ArnaudNorel95** [comment]
> 得先在电脑上用adb启动你手机的frida-server

forget all the other answers the key is here : You have to start your phone's frida-server with adb on your computer.

**Comment by securix01** [comment]
It is because of the version mismatch in frida-tools and frida server on the phone. Once you match the version eg: 16.x.x  then the error should not be there, provided:- 

# adb shell
# su
# cd /data/local/tmp
# chmod 777 frida-server-16.6.6-android-x86_64 
and # ./frida-server-16.6.6-android-x86_64 on the emulator ( I was using it for testing)

**Comment by ErrorxCode** [comment]
> > 得先在电脑上用adb启动你手机的frida-server
> 
> How is this still an issue?
> 
> For anyone else who is losing their mind over the frida api run this and it should sort out your misery:
> 
> `adb -s <ip>:5555 shell "su -c 'nohup /data/local/tmp/server -l 0.0.0.0:27042 &'"` Then CTRL+C and _should be all good_.
> 
> Smiley fucking face.

Hey thnx, it worked. Just curious how it did?
