### ISSUE TITLE
Which version is really working.

### ISSUE THREAD

**Issue by Ezriral** [frida/frida#2378]
From time to time im coming back to this project (4times i guess) cause i just wanna finally use and test it. But it never works.

latest version 16.0.8 (server is 16.0.8 arm/arm64) (windows frida is also 16.0.8)

Devices:
MEmu, Nox and real devices Samsung A022F (rooted / ARM), Samsung S6 (rooted / ARM64).
Frida:
using "frida-server &" and Magisk Frida 16.0.8 (tcp connection no usb)

the only thing what is working is "frida -U" and then i get the list of processes
but everything like attaching or starting apps i always get
=> Failed to attach: unable to connect to remote frida-server: closed
=> No frontmost application on SM-G965N
=> Failed to spawn: need Gadget to attach on jailed Android; its default location is: C:\Users\phant\AppData\Local\Microsoft\Windows\INetCache\frida\gadget-android-arm64.so

So is it me or is it that only every 10th version of this project is working and the rest is just not. When i reading about people telling each other "hey yeah its not working so use the version from last year lol".

I would be really happy if someone with a working frida system could tell me what version he/she is using and their setup.

Thank you

**Comment by oleavr** [comment]
Sorry to hear that. I'm afraid the configurations you've been testing on have historically only been supported by accident — due to the fragmented nature of the Android ecosystem, and us depending on some system internals, we cannot support all possible devices and ROMs. (Unless you help us out by debugging issues on yours.)

Currently we only officially support ROMs that are close to AOSP, such as Pixel phones. Samsung is known to customize things across the board, so such devices are among the least supported. Non-Google emulators are only tested occasionally, so YMMV there as well.

We do want to support these things though, but we are severely understaffed and are dependent on volunteers for this to happen.

**Comment by Ezriral** [comment]
understandable, my knowledge about your project is to high for me so i will not be a big help.
But it helps me to know what devices will probably work and which not.

Thank you

**Comment by sourcecodere** [comment]
@Ezriral Use frida 15 on Samsung. Not sure what is stopping frida 16, but something is.. This version combo works on my rooted s20:

```sh
pip install frida==15.2.2 frida-tools==11.0.0
```
```sh
/data/local/tmp # ./frida-server-15.2.2-android-arm6
```

**Comment by Redhat292** [comment]
I  am trying to install frida 16.3.3 into the nox emulator, frida server is 16.3.3. when run the objection, I am getting "connection terminated" error.

**Comment by yokrysty** [comment]
+1 for the table
