### ISSUE TITLE
How to switch realm to perform different operation

### ISSUE THREAD

**Issue by Chensem** [frida/frida#2398]
Problems below 
`realm=emulated` can't use Java api
![image](https://user-images.githubusercontent.com/27469499/215938862-8241f53c-8b81-401b-acf4-db7ee35bc4cf.png)
switch to native can use Java api
![image](https://user-images.githubusercontent.com/27469499/215938921-d54db1c8-98b2-49f3-a01c-b9a0da2a3a1c.png)
i want to coding use Java Api and realm=emulated at the same time , how to fix the problem

**Comment by pnill** [comment]
How did you end up resolving this, I know about the realms; oleavr in the past seemed to suggest operating in both simultaneously was possible but I'm trying to get my script to execute only after a specific JNI lib is loaded and when passing --realm=native I don't see it, when passing --realm=emulated and trying to access the java runtime to enumerate libs I'm unable to do so because I get a similar error to what you'd reported.

**Comment by Umokazan** [comment]
Any Solutions ?
