### ISSUE TITLE
QNX ARM backend

### ISSUE THREAD

**Issue by s1341** [frida/frida#25]
It would be great to be able to use frida on QNX ARM targets.

How do I go about adding a new platform backend to frida? What do I need to implement?

**Comment by oleavr** [comment]
That would be awesome! There are two components where you'll have to make modifications:
- frida-gum: This is Frida's platform library, which provides code instrumentation and many low-level goodies. It's written in C and you can piggyback on a lot of its existing code as ARM is already well-supported; you will just have to add the OS specific bits.
- frida-core: In this one it is all about providing language bindings, e.g. frida-python and frida-node, with an API that lets them enumerate available devices, and given a device enumerate its live processes, attach() to them, or spawn() a new one in suspended state to attach() to and later resume(). attach() returns a Session on which you can create_script(), post_message() to that script, receive a message from it. Now what attach() does is to inject a shared library into the target process. This shared library lives in frida-core/lib/agent, and provides the logistics for getting frida-gum into a target process, and maintaining a two-way communication channel with it over a platform-specific transport (frida-core/lib/pipe).

So, to cut to the chase, these are the steps:
- Build the SDK for `qnx-arm`:
```sh
$ make -f Makefile.sdk.mk FRIDA_HOST=qnx-arm
```
- Attempt to build frida-gum, which will build capstone for you and at least start the process of compiling it:
$ make -f Makefile.linux.mk build/frida-qnx-arm/lib/pkgconfig/frida-gum-1.0.pc
- Then get frida-gum's tests to pass, through rinse and repeat of something along the lines of:
```sh
$ cd frida-gum
$ (. ../build/frida-env-qnx-arm.sh && make -C ../build/tmp-qnx-arm/frida-gum) && scp ../build/tmp-qnx-arm/frida-gum/tests/gum-tests targetdevice:/tmp/ && ssh targetdevice /tmp/gum-tests"
```
This will mostly be about adding missing gum/backend-*/ bits, as you get the gum/arch-*/ bits for free as ARM is already supported. You can always add stubs here if you think certain features are not that important (e.g. you will definitely not want to write a Stalker backend, which I only got around to doing on x86 for now).
- Attempt to build frida-core, just to start the process of compiling it. Then you can rinse and repeat like above. In this case you will need to add src/qnx/*, similar to the exising src/<os> examples. This is essentially about writing a shared library injector and a spawn() implementation. You can defer the spawn() part if you don't need it, but the injection is required (because it's used even when you spawn(), as a second step before calling resume() to let the main thread execute the entrypoint).
- Add build steps to the top-level Makefile for the build OS where you'd like to do the cross-compilation. For example `Makefile.linux.mk`.

That should be it. Please do not hesitate to poke me if anything's unclear as you go along.

**Comment by s1341** [comment]
A couple of questions:
1. How can I configure frida to build target components using an existing QNX cross-toolchain?
2. What is the absolute minimum required to be implemented in order to get working code injection?

**Comment by oleavr** [comment]
1. Edit `releng/setup-env.sh`.
2. The absolute minimum is what I went through above; though you can of course disable tests that are failing and only add stub implementations. (The reason I suggested using the tests is that they will guide you through the parts that will otherwise fail further down the line.)

**Comment by oleavr** [comment]
Let's close this now that the preliminary support has landed thanks to the awesome work of @s1341.
