### ISSUE TITLE
how to get double value from args?

### ISSUE THREAD

**Issue by hellofrida** [frida/frida#266]
objective-c 
if args is int , args[2].toInt32() , it works,
but    args[2] is double ,it not works, 

i try to Memory.readDouble,Memor.readFloat,but fail,value is 0,
how to get double or float?

 Frida 9.1.13
  iphone4/frida-32

**Comment by oleavr** [comment]
Hi,

When working with floating point arguments, structs passed by value, etc. you have to use `Interceptor.replace()` and `NativeCallback` to have such arguments properly marshalled for you. There is currently no way to achieve this with a listener (`Interceptor.attach()`), as it does not know anything about the function's actual signature (by design).

Cheers!

**Comment by hellofrida** [comment]
thanks alot
