### ISSUE TITLE
Failed to attach to windows target

### ISSUE THREAD

**Issue by TobiasGrossUL** [frida/frida#2964]
When trying frida on windows with
`frida c:\Windows\System32\notepad.exe`
I receive the following error:
`Failed to attach: unexpectedly failed with error code: 0x00000057`
I can not find a solution online for this problem. Have you any idea?

When using frida in a python script I receive the same error but more details:
`    session = frida.attach(target_process)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
File "C:\Program Files\Python312\Lib\site-packages\frida\__init__.py", line 95, in attach
    return get_local_device().attach(target, realm=realm, persist_timeout=persist_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
File "C:\Program Files\Python312\Lib\site-packages\frida\core.py", line 86, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  
File "C:\Program Files\Python312\Lib\site-packages\frida\core.py", line 1071, in attach
    return Session(self._impl.attach(self._pid_of(target), **kwargs))  # type: ignore
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frida.NotSupportedError: unexpectedly failed with error code: 0x00000057`

**Comment by HexKitchen** [comment]
Same here. Testing on Frida 16.5.1, I find it succeeds on Windows 11 Enterprise 23H2 22631.3880 x64 but fails on Windows 10 Pro 22H2 19045.4780 x64.

The reason seems to be that in 16.5.1, Frida uses `GetProcessInformation` with `ProcessMachineTypeInfo`, which [reportedly](https://stackoverflow.com/questions/75339368/how-to-consistently-tell-windows-process-architecture) is not supported on Windows 10. Code: https://github.com/frida/frida-gum/blame/3a7b1642281b7bcae9cb622f81a2ad61558f1c20/gum/backend-windows/gumprocess-windows.c#L1252 The first Frida version with this change is 16.5.0.

**Comment by AnxiangLemon** [comment]
ver: `frida 16.5.1`
error: `FError: Unexpectedly failed with error code: 0x00000057`

I was originally injecting frida-H remotely
But due to the error prompt, I had to test it locally
Firstly, a frida server was enabled on Windows 10
`frida-server-16.5.1-windows-x86_64.exe -l 0.0.0.0:8080`

And then it was executed

![image](https://github.com/user-attachments/assets/837a2e0f-b80a-4094-99dd-4c03f32a77c7)

**Comment by AnxiangLemon** [comment]
> 我也是。在 Frida 16.5.1 上测试，我发现它在 Windows 11 Enterprise 23H2 22631.3880 x64 上成功，但在 Windows 10 Pro 22H2 19045.4780 x64 上失败。
> 
> 原因似乎是在 16.5.1 中，Frida 使用了`GetProcessInformation`with `ProcessMachineTypeInfo`，[据报道](https://stackoverflow.com/questions/75339368/how-to-consistently-tell-windows-process-architecture)Windows 10 不支持该功能。代码：[https](https://github.com/frida/frida-gum/blame/3a7b1642281b7bcae9cb622f81a2ad61558f1c20/gum/backend-windows/gumprocess-windows.c#L1252) ://github.com/frida/frida-gum/blame/3a7b1642281b7bcae9cb622f81a2ad61558f1c20/gum/backend-windows/gumprocess-windows.c#L1252第一个具有此变化的 Frida 版本是 16.5.0。

Thank you. I tried using frida 16.4.10 to solve this problem

**Comment by Aholicknight** [comment]
> Thank you. I tried using frida 16.4.10 to solve this problem

@AnxiangLemon what about for installing `frida-tools`?

**Comment by oleavr** [comment]
Thanks for reporting! This is fixed in Frida 16.5.8, just released.

**Comment by enrd214** [comment]
> Just ran into this trying out frida for the first time. I'll try downgrading to 16.4 for now.
> 
> Edit: installing frida-tools 12.5.1 worked for me (includes frida 16.4.10)

how can I downgrade frida on windows?

**Comment by joostrijneveld** [comment]
I just installed frida-tools 14.4.5 (current version on PyPI, installs frida 17.3.2) and I'm also running into this. Is that a regression or am I holding it wrong? Running Windows 11 ARM on an M1 Mac in VMware Fusion.

I tried reverting to the versions listed above (tools 12.5.1 with Frida 16.4.10), which instead crashes notepad.exe and tells me `frida.ProcessNotRespondingError: process with pid 3672 either refused to load frida-agent, or terminated during injection`. The version 16.5.8 you mention is missing from PyPI, and installing 16.5.9 triggers the error from the original post.

EDIT: Just noticed https://github.com/frida/frida/issues/3393 which led me to believe it is related to an x86/ARM issue. I'm running Python using uv, which ships CPython for x86, with Windows taking care of the emulation layer. It appears I'm running into the same errors regardless of whether I'm attaching to an ARM or emulated x86 process.
