### ISSUE TITLE
issue frida-server in android

### ISSUE THREAD

**Issue by vah13** [frida/frida#41]
hi.
I use android in genymotion x86. when I downloaded frida-server for arm and try run write 

frida-server not executable magic 7f45

I install arm translator but don't help me, continue write 

frida-server not executable magic 7f45.
Anybody know how fix it?

**Comment by oleavr** [comment]
Hi,

x86 Android isn't fully supported yet; I initially ported it but realized I've taken on too many platforms to maintain, so I dropped it for the time being. If you'd like to build Frida yourself for Android/x86 and stabilise it then that would be awesome, but otherwise I'm afraid you'll have to use an Android/ARM emulator.

Cheers!

**Comment by vah13** [comment]
ok, thank you

**Comment by hubert3** [comment]
I assume there's no change here and x86 isn't currently supported.

I'd also love to use Genymotion (virtualbox/x86 based Android emulator) as it runs many times faster than ARM-based emulators for me.

Any pointers for what needs to be implemented to make an x86 frida-server work?

PS, I was super impressed that make server-android compiled arm & arm64 server binaries out of the box after git clone

**Comment by oleavr** [comment]
@hubert3 Everything is ported except for the Dalvik integration, where some struct offsets probably don't match Android/ARM (untested). Last time I tried the x86 frida-server I did however experience random crashes when injecting, but I didn't have time to investigate. There have been generic improvements and fixes to the injector since then, so this might be working better now. If you could build the server yourself and take it for a spin, that would be great. All you need to do is:

```
$ make build/frida_stripped-android-i386/bin/frida-server
```

**Comment by haomnguyen** [comment]
I saw there's Frida for Android x86 in your latest release, is it a stable build?

**Comment by oleavr** [comment]
@haomnguyen Yes it is fully supported.

**Comment by cse001** [comment]
We can find all the related frida-servers as well as other resources over here 
https://github.com/frida/frida/releases
