### ISSUE TITLE
Process crash when jumping back to traced function(android on arm)

### ISSUE THREAD

**Issue by pavel-lazar** [frida/frida#45]
Hi,

When trying to attach to the function android_getaddrinfoforiface on netd after doing the first resolving there is a process crash with null deref when the functions tries to reload the __stack_chk_guard value from stack. 
Attaching a debugger to the process and trying to debug the issue (by putting a breakpoint on the traced function) was quit difficult due the fact that the breakpoint is being hit from different threads. 
This multiple threads might be also the core reason of the crash (I am not sure the intercepting logic is thread safe), but I am not sure.

To reproduce the issue just start an emulator (or a device) and run the default trace function (frida-trace -R -i android_getaddrinfoforiface netd), then do any host resolving (with a browser) and you will see the crash.

**Comment by oleavr** [comment]
Hey,

Thanks for reporting! This is most likely caused by the implementation having a position-dependent instruction early in its prologue, and we fail to relocate it properly. Beware of setting breakpoints with a debugger, as it will get confused as we rewrite the start of the function in memory.

Could you disassemble the first instructions of the function (with their opcodes) and paste here?

Cheers!

**Comment by pavel-lazar** [comment]
I have attached after the write so hopefully gdb should not care. Any way, here is the original  disassembled function (taken from IDA):
.text:00035C90 2D E9 F0 4F                 PUSH.W          {R4-R11,LR}
.text:00035C94 CD B0                       SUB             SP, SP, #0x134
.text:00035C96 90 46                       MOV             R8, R2
.text:00035C98 DF F8 68 27                 LDR.W           R2, =(__stack_chk_guard_ptr - 0x48FD8)
.text:00035C9C 0D 93                       STR             R3, [SP,#0x158+var_124]
.text:00035C9E 05 46                       MOV             R5, R0
.text:00035CA0 DF F8 64 37                 LDR.W           R3, =(_GLOBAL_OFFSET_TABLE_ - 0x35CAC)
.text:00035CA4 0E 46                       MOV             R6, R1
.text:00035CA6 57 9F                       LDR             R7, [SP,#0x158+arg_4]
.text:00035CA8 7B 44                       ADD             R3, PC ; _GLOBAL_OFFSET_TABLE_
.text:00035CAA DF F8 60 07                 LDR.W           R0, =(aAndroid_dns_mo - 0x35CB4)
.text:00035CAE 0C 97                       STR             R7, [SP,#0x158+var_128]
.text:00035CB0 78 44                       ADD             R0, PC  ; "ANDROID_DNS_MODE"
.text:00035CB2 9C 58                       LDR             R4, [R3,R2] ; __stack_chk_guard
.text:00035CB4 23 68                       LDR             R3, [R4]
.text:00035CB6 4B 93                       STR             R3, [SP,#0x158+var_2C]
.text:00035CB8 F2 F7 D6 F9                 BL              getenv

and here is the disassembled function after hooking it with frida and attaching with gdb:
Dump of assembler code from 0xb6e9ac91 to 0xb6e9accd:
   0xb6e9ac91:	b5 01	push	{r0, r1, r2, r3, r4, r5, r6, r7, lr}
   0xb6e9ac93:	48 00	ldr	r0, [pc, #4]	; (0xb6e9ac98)
   0xb6e9ac95:	47 90	bx	r0
   0xb6e9ac97:	46 05	mov	r8, r2
   0xb6e9ac99:	12 f2	asrs	r5, r0, #8
   0xb6e9ac9b:	b6 0d			; <UNDEFINED> instruction: 0xb6f2
   0xb6e9ac9d:	93 05	str	r3, [sp, #52]	; 0x34
   0xb6e9ac9f:	46 df	mov	r5, r0
   0xb6e9aca1:	f8 64 37 0e	ldr.w	r3, [pc, #1892]	; 0xb6e9b408
   0xb6e9aca5:	46 57	mov	r6, r1
   0xb6e9aca7:	9f 7b	ldr	r7, [sp, #348]	; 0x15c
   0xb6e9aca9:	44 df	add	r3, pc
   0xb6e9acab:	f8 60 07 0c	ldr.w	r0, [pc, #1888]	; 0xb6e9b40c
   0xb6e9acaf:	97 78	str	r7, [sp, #48]	; 0x30
   0xb6e9acb1:	44 9c	add	r0, pc
   0xb6e9acb3:	58 23	ldr	r4, [r3, r2]
   0xb6e9acb5:	68 4b	ldr	r3, [r4, #0]
   0xb6e9acb7:	93 f2	str	r3, [sp, #300]	; 0x12c
   0xb6e9acb9:	f7 d6 f9 00	bl	0xb6e8d068
   0xb6e9acbd:	21 20	movs	r1, #0
   0xb6e9acbf:	22 0e	movs	r2, #32
   0xb6e9acc1:	90 17	str	r0, [sp, #56]	; 0x38
   0xb6e9acc3:	a8 ec	add	r0, sp, #92	; 0x5c
   0xb6e9acc5:	f7 7c ea 00	blx	0xb6e871c0
   0xb6e9acc9:	20 0f	movs	r0, #0
   0xb6e9accb:	94 1f	str	r4, [sp, #60]	; 0x3c
End of assembler dump.

And the crash is always in 0x****0cb4.
(I haven't noticed the strange instructions in c99 and c9b yesterday)

**Comment by oleavr** [comment]
Thanks! So, for Thumb functions we currently copy at least the first 12 bytes as you can see [here](https://github.com/frida/frida-gum/blob/29d0b7abeb8961d2705ade774ca531e3c6907482/gum/backend-arm/guminterceptor-arm.c#L20), potentially more with mixed length Thumb instructions (to not cut an instruction in half). The issue is that when we copy (relocate) the instructions [here](https://github.com/frida/frida-gum/blob/29d0b7abeb8961d2705ade774ca531e3c6907482/gum/backend-arm/guminterceptor-arm.c#L136-L141), there must be one of the instructions that is position-dependent that we don't rewrite correctly. Looking at the instructions you pasted, it must be `LDR.W R2, =(__stack_chk_guard_ptr - 0x48FD8)`. Looking at the test-suite, I see that we currently handle the narrow `ldr pc` instruction according to [this test](https://github.com/frida/frida-gum/blob/29d0b7abeb8961d2705ade774ca531e3c6907482/tests/core/arch-arm/thumbrelocator.c#L79-L108), but not the wide one. So this should just be a matter of adding another test there for the wide version of the instruction, and implementing it in the ThumbRelocator to make the test pass. I'm very right now, so if you feel like taking a stab at this then that would be awesome. (If not I can have a look at it in the near future.)

**Comment by oleavr** [comment]
Success:

```sh
$ frida-trace -R -i android_getaddrinfoforiface com.android.browser
Instrumenting functions...
Started tracing 1 function. Press ENTER to stop.
   7460 ms       android_getaddrinfoforiface()
 13436 ms       android_getaddrinfoforiface()
 14837 ms       android_getaddrinfoforiface()
 20836 ms       android_getaddrinfoforiface()
 25437 ms       android_getaddrinfoforiface()
 32838 ms       android_getaddrinfoforiface()
 49439 ms       android_getaddrinfoforiface()
 56840 ms       android_getaddrinfoforiface()
 97440 ms       android_getaddrinfoforiface()
104841 ms       android_getaddrinfoforiface()
```
