### ISSUE TITLE
How to new Toast.makeText() attach Activity.onStart()?

### ISSUE THREAD

**Issue by GeekTan** [frida/frida#452]
```
'use strict';
Java.perform(function(){

    var Toast = Java.use("android.widget.Toast");

    var Activity = Java.use("android.app.Activity");

    Activity.onStart.implementation = function(){

        console.log(this);
        var instance = Toast.$new(this);
        instance.makeText(this,"hello",1);
        this.onStart.call(this);
    }


});
```
My code is this,but not show toast

**Comment by ChD1** [comment]
And in the log there is a record console.log (this) ;? I certainly can be wrong, but I think that you hook code starts after Activity.onStart executed. In a frida, this is a problem, an early interception of Java. Some methods executed before the interception. I even built in the Application.onCreate method sleep instructions (smali) for pausing program execution so that the frida code had time to work.

**Comment by iddoeldor** [comment]
did you manage to make it work ?
