### ISSUE TITLE
How to use frida to hook a native function's arguments in Android?

### ISSUE THREAD

**Issue by bxl0608** [frida/frida#491]
Hello,Recent,I learn to use the frida framework，but i met a problem. 
I have a native function, i know it has three argumens,fisrt is a Int, the second is String,i can print the first argument,but the second argument .i don't konw how to print it. code like this:

Interceptor.attach(Module.findExportByName("libuserinfo.so", "getString"),{
        onEnter: function (args) {
            send(args[2].toInt32());  // this is first argument.
            // this.buf = args[3];    how can i print the second argument?
        },
        onLeave: function (retval) {
         
        }
});

**Comment by don1001** [comment]
is it ASCII string ? try 

``` log(Memory.readUtf8String(args[3]));  //log 4th argument```

**Comment by oleavr** [comment]
Use `Memory.readCString()` if you're uncertain about the encoding. Use `Memory.readUtf8String()` if you're sure it's valid UTF-8 – otherwise it will throw a JS exception, whereas `Memory.readCString()` will try to decode as UTF-8, where bytes that can't be interpreted as valid Unicode are replaced with the Unicode replacement character. (Frida uses [g_utf8_make_valid()](https://developer.gnome.org/glib/stable/glib-Unicode-Manipulation.html#g-utf8-make-valid) behind the scenes.)

**Comment by duolaaa** [comment]
@oleavr  hi , in this problem, how can i modify the argument( two String arguments)? like this ? or i should new a nativefunction ? thank you.

```
var a3 = Memory.allocUtf8String("bW9iaWxlUG");
args[3] = a3 
```
or 


```
var env = Java.vm.getEnv();
 var handle = env.handle;
var f = new NativeFunction(stringFromJNI, 'pointer',['pointer','pointer','pointer','pointer']);
var result = f(handle,ptr('0x0'),a2,a3);
consolo.log(result);
```
