### ISSUE TITLE
Unable to install Frida on windows -10

### ISSUE THREAD

**Issue by manish199014** [frida/frida#563]
Hello, 
I am getting the following error while installing Frida. 

I used the following command to install: pip install frida-tools. 

<img width="1061" alt="screen shot 2018-07-20 at 4 51 15 pm" src="https://user-images.githubusercontent.com/14213944/42999913-36be5642-8c3d-11e8-9c2f-73f2ad19f915.png">

**Comment by minhtt159** [comment]
Please use another OS, even if you can install successfully, the iTunes driver will not recognize your phone properly.

**Comment by oleavr** [comment]
@manish199014 This is a Python configuration issue. The certificate store used by Python 3 on your system is probably empty and needs to be initialized. This is covered in the Python docs. (Check the README.)

@minhtt159 Frida is also useful for instrumenting Windows apps... and I'm not aware of any issues with iOS devices on Windows, so that sounds like a hardware/driver issue on your end.
