### ISSUE TITLE
How to call methods in Frida Gadget (JavaScript API iOS)?

### ISSUE THREAD

**Issue by ddzobov** [frida/frida#567]
i have class [ClassName] and method [- setSomething].

How can i call with JS API withount Interceptor this method?

**Comment by mrmacete** [comment]
You have to get an instance of the object first, either:
- allocating it and calling its constructor, for example `var instance = ObjC.classes.ClassName.alloc().init();`
- getting an existing instance using `ObjC.choose`, like - if you know there's only one instance - you can to something like `var instance = ObjC.chooseSync(ObjC.classes.ClassName)[0];`
- getting an existing instance from a singleton you know holds the instance in a property, for example `var instance = ObjC.classes.MySingleton.getInstance().myInterestingInstance();`

and then call the method on the instance:
```
instance.setSomething();
```

or, if the method signature takes an argument, like `- setSomething:`, you can also pass the argument (just remember to put a `_` instead of ObjC's `:`):

```
instance.setSomething_(argument);
```

btw, you can find few example of this here: https://www.frida.re/docs/examples/ios/

**Comment by ddzobov** [comment]
Thank you!

How can i enumerate arguments of method?

**Comment by ddzobov** [comment]
Thank you for explanation!

**Comment by xiaomiwang** [comment]
Hi, I have some questions.
When the function has two or more arguments, how can I call this function by JavaScript.
And how can I pass nil as argument?

plz, Thanks.
