### ISSUE TITLE
Problem while bulding  make -f Makefile.sdk.mk

### ISSUE THREAD

**Issue by 3125788** [frida/frida#580]
I'm trying to compile Frida at Ubuntu 16.04.1, and at make -f Makefile.sdk.md, I met the following error, which looks like ffi.h has not been generated correctly, because the code contains the variable @STATIC@.

After I have annotated the corresponding macro definition, the compilation can be completed, but I want to know why.

Here's the wrong message：

In file included from ../../../libffi/src/x86/unix64.S:32:0:
include/ffi.h:56:5: error: token "@" is not valid in preprocessor expressions
 #if @STATIC@
     ^
Makefile:1211: recipe for target 'src/closures.lo' failed
make[3]: *** [src/closures.lo] Error 1
Makefile:1187: recipe for target 'src/x86/unix64.lo' failed
make[3]: *** [src/x86/unix64.lo] Error 1
make[3]: Leaving directory '/home/zhenghaofang/frida/build/fs-tmp-linux-x86_64/libffi'
Makefile:1285: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/zhenghaofang/frida/build/fs-tmp-linux-x86_64/libffi'
Makefile:578: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/zhenghaofang/frida/build/fs-tmp-linux-x86_64/libffi'
Makefile.sdk.mk:365: recipe for target 'build/fs-linux-x86_64/lib/pkgconfig/libffi.pc' failed
make: *** [build/fs-linux-x86_64/lib/pkgconfig/libffi.pc] Error 2

**Comment by oleavr** [comment]
The issue is that `Makefile.sdk.mk` picks the latest `master` of each repo, i.e. does not pin to certain commits. I'm currently working on finishing the [dependency-upgrades](https://github.com/frida/frida/tree/dependency-upgrades) branch, which is able to build the latest SDK, at least on macOS. That won't help you much though, as I'm still working on porting to the new APIs. So as a workaround in the meantime you could try hacking `Makefile.sdk.mk` so it fetches older revisions of each git submodule.

**Comment by 3125788** [comment]
I would try to hacking it. But I want to know witch branch is stable? Could you give me more advice to hacking that file?
Thanks!
