### ISSUE TITLE
Frida 4.4.0 Stalker.follow() Crashes process. Win8.1 x86_64, JS Bindings

### ISSUE THREAD

**Issue by nbsdx** [frida/frida#63]
The following hook crashes the target process. It only crashes when trying to use Stalker, other operations seem to work fine.

``` javascript
    "use strict";

    const async = require( 'generator-async' );
    const frida = require( 'frida' )

    let session, script;
    async.run( function* () {
        "use strict";
        session = yield frida.attach( 'a.exe' );
        script = yield session.createScript( '(' + agent.toString() + ').call( this );' );
        script.events.listen( 'message', message => {
            console.log( message );
        } );
        yield script.load();
    } );

    function agent() {
        "use strict";
        Stalker.follow( {
            events: { call: true },
            onReceive: function( e ) {
                send( {name:'debug', data:'onReceive'} );
            },
            onCallSummary: function( e ) {
                send( {name:'debug', data:'onCallSummary'} );
            }
        } );
    }
```

**Comment by nbsdx** [comment]
As a follow up, it looks like on Linux the only results I'm getting to `onReceive` and `onCallSummary` are addresses of a function inside Frida's injected library. I'm in the process of building and trying to debug what's going on.

**Comment by oleavr** [comment]
Ooh. The documentation isn't too clear, but if you omit the first argument to `Stalker.follow()` it will follow the current thread. In the example above that thread is one of Frida's threads (which is among the threads filtered out from `Process.enumerateThreads()`). We also configure the underlying `Stalker` implementation so that it tries to avoid stalking into Frida's code range, so that's another reason you get very little output (not that tracing one of Frida's threads would give you anything of interest anyway).

So what you should do here is either stalk one or more of the thread ids given to you by `Process.enumerateThreads()`, or directly from a synchronous callback from the application's code, e.g. `Interceptor.attach()`'s `onEnter` or `onLeave` callbacks.

Hope this makes things a bit clearer!

**Comment by nbsdx** [comment]
Ah okay. So I changed my code to

```javascript
    function agent() {
        "use strict";
        Process.enumerateThreads( {
            onMatch: function( thread ) {
                Stalker.follow( thread.id, {
                    events: { call: true },
                    onReceive: function( e ) {
                         send( {name:'debug', data:'onReceive'} );
                    },
                    onCallSummary: function( e ) {
                        send( {name:'debug', data:'onCallSummary'} );
                    }
            },
            onComplete: function() {} // do nothing
        } );
    }
```

and that doesn't crash, but I don't get any responses from Stalker. I tried following `thread.id` as well, but that caused a crash. The program that I'm testing on is the simple 'print number, sleep, repeat' program, so I would expect ~3 calls per iteration: foo, printf, sleep, + any calls in printf. I can see that the process I'm attaching to is still running, and no error messages are thrown. 

Additionally, `onComplete` is never called. If I put a `send()` in there, it's never called unless I force `onMatch` to end with `return "stop"`. `Process.enumerateThreadsSync()` just hangs, then eventually returns a timeout error, and no further execution is done in `agent()`

**Comment by oleavr** [comment]
Should be fixed in latest Frida 9.x.

**Comment by crifan** [comment]
for my case, `Stalker.follow` crashed, the solution is:

* Use [Stalker.exclude(range)](https://frida.re/docs/stalker/#excluded-ranges) to exclude common module/libs.
  * For details, pls refer [another answer](https://github.com/frida/frida/issues/244#issuecomment-2530595856)
