### ISSUE TITLE
[Android native ] How to replace the new value?

### ISSUE THREAD

**Issue by henrytom1703** [frida/frida#660]
Hello guys.
I want replace  the new value in below? Anyone, Could you help me do it?
Thanks.

```

**Comment by mohe2015** [comment]
```javascript
var getInfoPtr = Module.findExportByName("libnative-lib.so", "_Z7getInfoP4info");
console.log(getInfoPtr); // check if found

// android emulator 9 + 7.1.1 don't work, use 5.0.2

Interceptor.attach(getInfoPtr, {
    onEnter: function (args) {
    	   console.log("onEnter");
         Memory.writeUtf8String(args[0], "thefirststring");
         Memory.writeUtf8String(new NativePointer(args[0]).add(50), "thesecondstring");
    }
});
```

**Comment by henrytom1703** [comment]
Hi @mohe2015 
If the struct has 4 properties then code will be same below, right?:
 Memory.writeUtf8String(args[0], "thefirststring");
 Memory.writeUtf8String(new NativePointer(args[0]).add(50), "thesecondstring");
Memory.writeUtf8String(new NativePointer(args[0]).add(50 * 2), "third");
Memory.writeUtf8String(new NativePointer(args[0]).add(50 * 3), "four");
Thanks

**Comment by mohe2015** [comment]
@henrytom1703 In normal cases, yes. But there may be [structure alignments](https://en.wikipedia.org/wiki/Data_structure_alignment) by the compiler etc. but I don't think that's the case with byte arrays. Just try it and if it doesn't work you can further investigate it.

**Comment by henrytom1703** [comment]
Thanks @mohe2015

**Comment by henrytom1703** [comment]
hi @mohe2015 
Thanks

**Comment by henrytom1703** [comment]
hi @mohe2015 
How to access and replace the value in struct  below?
 + ifreq(struct) --access-> ifr_ifru --access -->ifru_hwaddr --access->sa_data
```
struct sockaddr {
  sa_family_t sa_family;
  char sa_data[14];
};

struct ifreq {
#define IFHWADDRLEN 6
  union {
    char ifrn_name[IFNAMSIZ];
  } ifr_ifrn;
  union {
    struct sockaddr ifru_addr;
    struct sockaddr ifru_dstaddr;
    struct sockaddr ifru_broadaddr;
    struct sockaddr ifru_netmask;
    struct sockaddr ifru_hwaddr;
    short ifru_flags;
    int ifru_ivalue;
    int ifru_mtu;
    struct ifmap ifru_map;
    char ifru_slave[IFNAMSIZ];
    char ifru_newname[IFNAMSIZ];
    void __user * ifru_data;
    struct if_settings ifru_settings;
  } ifr_ifru;
};
```

**Comment by henrytom1703** [comment]
hi @mohe2015 
How to access and replace the value in struct  below?
 + ifreq(struct) --access-> ifr_ifru --access -->ifru_hwaddr --access->sa_data
```
struct sockaddr {
  sa_family_t sa_family;
  char sa_data[14];
};

struct ifreq {
#define IFHWADDRLEN 6
  union {
    char ifrn_name[IFNAMSIZ];
  } ifr_ifrn;
  union {
    struct sockaddr ifru_addr;
    struct sockaddr ifru_dstaddr;
    struct sockaddr ifru_broadaddr;
    struct sockaddr ifru_netmask;
    struct sockaddr ifru_hwaddr;
    short ifru_flags;
    int ifru_ivalue;
    int ifru_mtu;
    struct ifmap ifru_map;
    char ifru_slave[IFNAMSIZ];
    char ifru_newname[IFNAMSIZ];
    void __user * ifru_data;
    struct if_settings ifru_settings;
  } ifr_ifru;
};
```
Thanks

**Comment by mohe2015** [comment]
@henrytom1703 I found it too difficult to do it by hand as every architecture has different sizes of data types and as there may be padding anywhere.
`static_assert(offsetof(struct ifreq, ifr_ifru.ifru_hwaddr.sa_data) == 18, "fail");`
So you would need to use `console.log(Memory.readUtf8String(NativePointer(ifreqPtr).add(18)));`
Explanation:
The ifreq struct contains two unions. The first union is before the second union which contains your targeted field. So we need to add the size of the first union which is IFNAMSIZ (16). As the second union is a [union](https://en.cppreference.com/w/cpp/language/union) the ifru_hwaddr struct is at offset 0. The sa_data field in the struct sockaddr comes after the sa_family_t sa_family which is an unsigned short (2 bytes). So 16+0+2 = 18.

How I found that out:
I used android studio and created a native project. I used `static_assert(offsetof(struct ifreq, ifr_ifru.ifru_hwaddr.sa_data) >= x, "fail");` to limit the possible range of the offset (see above). Then I tried different values for x. To compile I changed directory to `MyApplication/app/.externalNativeBuild/cmake/debug/armeabi-v7a` and ran ninja. If the build fails the assert was wrong and my x was too high. Otherwise x was not high enough of correct so I incremented it. In the end I got the correct value.

P.S.: I didn't test if that works so please tell me if it didn't.

**Comment by mohe2015** [comment]
@henrytom1703 You may also check out the [telegram channel or IRC](https://frida.re/contact/) as most people don't like guiding questions in github issues.
