### ISSUE TITLE
Failed to spawn: the connection is closed 

### ISSUE THREAD

**Issue by Blueskysun** [frida/frida#702]
Failed to spawn: the connection is closed 
frida is 12.2.24
I am in Android 4.4  32 ,frida will restart devices and tell me Failed to spawn: the connection is closed 
I wish the problem will be solved.thanks

**Comment by prettywolf** [comment]
i got the same error when run frida -U -f com.google.xxxx
but script is ok,frida-server is newest

**Comment by CeruleanSky** [comment]
I am on Android 4.4.2 using 12.4.48 and it times out

>frida-trace -i open -U -f com.android.chrome
>Failed to spawn: the connection is closed

12.5.0 crashes and says unsupported linker as per #868

**Comment by hustwyk** [comment]
I meet the same problem just now. My pixel XL displays the start up logo "Google" after I type `frida -U -f com.android.chrome --no-pause`. And then I check if frida-ps works or not, and luckly it still works. But when I type `frida -U -f com.android.chrome --no-pause` again, frida shows `Failed to spawn: the connection is closed`. Then I check the android processes: `adb shell ps | grep frida`, and I find the `frida-server` is not running ! Then I re-run the frida-server and now everything works fine.

**Comment by Evildoer-ss** [comment]
Try a lower version.
I also had the same problem before, and the problem was solved by changing to the lower version 11.0.13, which is the last version supported by python2.

**Comment by oleavr** [comment]
@Evildoer-ss Python 2 is still supported, that was a regression which was fixed not that long ago.

Note that old versions are unsupported, and encouraging users to downgrade is not helpful as it means they will run into old bugs that we've already fixed. Would appreciate help in tracking down regressions instead – they're often very easy to fix.

As this issue is quite old and I've seen many reports of latest Frida working well, it should be safe to assume that this issue has already been resolved.
