### ISSUE TITLE
Failed to attach - iOS 12.0.1

### ISSUE THREAD

**Issue by daukstsoskars** [frida/frida#792]
Cannot attach to any application

**Device:**

* Jailbroken iOS 12.0.1 with unc0ver jailbreak.
* CPU: A10X
* OS Build: 16A404

**Versioning (iOS device and computer):**
```
frida --version
12.4.0
```
**Doesn't work**
```
frida -U <app> -l <script.js>
Failed to attach: expecting to read a single byte for receiving credentials but read zero bytes' 
``` 
**Works**
```
//Works just fine
frida-ps -U
```

**Comment by Daemonceltics** [comment]
iOS 11.4.1 with unc0ver jailbreak
$ frida-ps -U
Failed to enumerate processes: the connection is closed
Device reboot!

**Comment by oleavr** [comment]
@daukstsoskars @Daemonceltics Please try Frida from git master, which supports unc0ver (except for app launching).

**Comment by mechanico** [comment]
@oleavr just downloaded https://github.com/frida/frida/releases/download/12.4.0/frida-server-12.4.0-ios-arm64.xz and run on my iOS 12.1.1-b3 device. (Copied to /usr/bin/ with scp, then run chmod +x, and finally started in Daemon mode -D.) Now it works like a charm.

Thanks for the advice!

**Comment by daukstsoskars** [comment]
I get the same issue as before, i checked my version of frida-server on the iOS and it looks like i am running latest version of frida on pc and iOS device.

```
//inside /usr/sbin
frida-server --version
2019-03-06 09:37:05.296 frida-server[3705:389197] === SSL Kill Switch 2: Preference file not found.
2019-03-06 09:37:05.296 frida-server[3705:389197] === SSL Kill Switch 2: Substrate hook disabled.
12.4.0
```

**Comment by MuchiMuchiPink** [comment]
12.4.0 is the latest release from last week but @oleavr did the commit yesterday. Correct me if I'm wrong. Couldn't compile the new Binary having no access to MacOS rn and the iOS toolchain.

**Comment by kernel-sanders** [comment]
I am having the reboot issues from #788 on iOS 11.1.2 unc0ver. Tried mechanico's solution but got the following:

```
iPhone:/tmp root# mv frida-server-12.4.0-ios-arm64 /usr/sbin/frida-server
iPhone:/tmp root# chmod +x /usr/sbin/frida-server 
iPhone:/tmp root# frida-server --version
12.4.0
iPhone:/tmp root# frida-server -D       
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
```

**Comment by AdamWang1102** [comment]
Same issue on iPhone6 iOS12.0 unc0ver. When I tap 'frida-ps -U' on my mac the phone crash & reboot with **Failed to enumerate processes: the connection is closed**

**Comment by herven90** [comment]
> @Daemonceltics just downloaded https://github.com/frida/frida/releases/download/12.4.0/frida-server-12.4.0-ios-arm64.xz and run on my iOS 12.1.1-b3 device. (Copied to /usr/bin/ with scp, then run chmod +x, and finally started in Daemon mode -D.) Now it works like a charm.

Hi Daemoncelitics,
can i check with you how do you execute the file (frida-server-12.4.0-ios-arm64.xz) in your iOS device? I have already chmod +x and moved the file to /usr/bin in my iOS device. However i am not sure what to do to proceed next.

iOS 11.3.1
Jailbroken via unC0ver

Thanks.

**Comment by ehvanr** [comment]
> Same issue on iPhone6 iOS12.0 unc0ver. When I tap 'frida-ps -U' on my mac the phone crash & reboot with **Failed to enumerate processes: the connection is closed**

I can confirm the same on iPhone X 12.1.2 unc0ver. Same result with the 12.4.0 `frida-server` binary as well.

**Comment by Daemonceltics** [comment]
> @daukstsoskars @Daemonceltics Please try Frida from git, which supports unc0ver (except for app launching).
iOS 11.4.1
$git pull new commit code and make ios-server, $frida-ps -U fine but attach failed.
Failed to attach: expecting to read a single byte for receiving credentials but read zero bytes

**Comment by mechanico** [comment]
@herven90,

As mentioned earlier, I was able to execute the frida-server but I'm also receiving the following error:

> Failed to attach: expecting to read a single byte for receiving credentials but read zero bytes' 

Unfortunately, I have no solution on this one until now. Falling back to lldb to extract unencrypted binaries and to patch the code flow... 

I will chase this one up later this week again, got several jailbroken devices (different CPU's) on 12.1.1-b3. Keep you up-to-date, here.

**Comment by Daemonceltics** [comment]
> @daukstsoskars @Daemonceltics Please try Frida from git, which supports unc0ver (except for app launching).

Thanks, it works.

**Comment by mechanico** [comment]
Thanks @oleavr, it worked.

On Mac:

- Download the frida repo
- Create a code signing certificate (https://sourceware.org/gdb/wiki/PermissionsDarwin#Create_a_certificate_in_the_System_Keychain)
- Export the certificate in environment variables

```
$ make
$ make server-ios-thin
```

- Copy the binary to the iOS device, e.g. with scp

On device:
- create ent.xml 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.springboard.launchapplications</key>
	<true/>
	<key>platform-application</key>
	<true/>
	<key>get-task-allow</key>
	<true/>
	<key>proc_info-allow</key>
	<true/>
	<key>task_for_pid-allow</key>
	<true/>
	<key>run-unsigned-code</key>
	<true/>
	<key>com.apple.system-task-ports</key>
	<true/>
</dict>
</plist>
```
- Run the following command on the frida-server binary
`$ ldid -Sent.xml /usr/sbin/frida-server`
- Start frida-server as a daemon
`$ frida-server -D`

On Mac, now everything works like a charm :), e.g. dumping unencrypted binaries.

**Comment by scugn1zz0** [comment]
@mechanico I’m sorry to bother you, could you please be a bit more detailed with the passages shown above?
What do you mean by downlod the frida repo? You mean downlod the source code to build it right?
Also how does exporting the certificate in environment variables work? Do I have to use the command “make” while I’m in the folder of both frida source code and the newly created certificate?

I’m really sorry to bother you, as you may have understood I am not a pro user at all, I’m learning, and when I got to know frida months ago, no jailbreak was available so I’m very excited in the idea of starting to use this tool now.
Thanks a lot

**Comment by kernel-sanders** [comment]
@scugn1zz0 Download the frida repo by cloning it:

`git clone https://github.com/frida/frida.git`

Follow the link on how to create a self signed code signing cert with Keychain Access, the export the name of that cert like so

`export IOS_CERTID=frida-cert`

macOS will lookup the cert in the keychain and it does not need to be in the frida directory.

On a 5S 11.1.2 I had to run frida in the foreground for it to work correctly.

**Comment by scugn1zz0** [comment]
Thanks a lot for the help @kernel-sanders.

Unfortunately I am having this error "Failed to enumerate processes: unable to connect to remote frida-server: Unable to connect (connection refused)"

As it is not installed or active on the iphone.
The device an iPhone X on iOS 12.1 jailborken with unc0ver 3.0.0~b45

What have i done:

- git cloned the repo
- created the system certificate
- `make` e `make server-ios-thin` (i think that the certificate "thing" worked properly because while building, Terminal app asked for my password to use the certificate)
- then i went into the cloned folder frida>build>frida_thin-ios-arm64>bin>frida-server and copied this file through ssh into my iPhone at `/usr/sbin/`
- then i put in the same directory `/usr/sbin/` the file ent.xml as said by @mechanico and added the line that you (@kernel-sanders suggested)
- then I did `ldid -Sent.xml /usr/sbin/frida-server`
- then `chmod +x frida-server`
- and `frida-server -D` (the anser i get from iphone is "Killed: 9")

...
Then I try the frida test: `frida-ps -U`
But i get: `Failed to enumerate processes: unable to connect to remote frida-server: Unable to connect (connection refused)`

P.S.) I tried both `/usr/bin/` and `/usr/sbin/` for doing this procedure, but I feel like something is missing.
P.S. 2) Previously i had installed frida from cydia repo, but before doing these procedures i removed it



A screenshot of the folder structure after building
<img width="496" alt="Screenshot 2019-03-13 at 22 55 31" src="https://user-images.githubusercontent.com/14803862/54317345-28728f80-45e3-11e9-8406-81d3a0881fb1.png">

**Comment by ehvanr** [comment]
This is working now as of Frida 12.4.1

**Comment by mechanico** [comment]
@scugn1zz0 did you make sure, that no other frida-server process is running? 
`$ ps -A | grep frida`

Btw if you get the "Killed 9" error, something is wrong with the signing. Maybe revisit the content of ent.xml.

**Comment by scugn1zz0** [comment]
Hey @mechanico and @ehvanr Thanks a lot for the precious help! now everything is up and running.
I can attach to process, and I can do `frida-trace -U -i "CCCryptorCreate*" Twitter` smoothly.

I can't really dump apps to be honest, using "frida-ipa-dump" or others, but I'm not a PRO user enough to say that it is due to frida.

Anyway, let me take this opportunity to ask you if there are official or unofficial irc or telegram channel to share tips and advices about frida usage (or even more in general iOS RE procedures).
Thanks a lot for the help.

To me this issue can be closed!

**Comment by evandrix** [comment]
> Hey @mechanico and @ehvanr Thanks a lot for the precious help! now everything is up and running.
> I can attach to process, and I can do `frida-trace -U -i "CCCryptorCreate*" Twitter` smoothly.
> 
> I can't really dump apps to be honest, using "frida-ipa-dump" or others, but I'm not a PRO user enough to say that it is due to frida.
> 
> Anyway, let me take this opportunity to ask you if there are official or unofficial irc or telegram channel to share tips and advices about frida usage (or even more in general iOS RE procedures).
> Thanks a lot for the help.
> 
> To me this issue can be closed!

dump:decrypted(.ipa) - used to be Clutch(2), then Rasticrac, now [CrackerXI](https://iosgods.com/topic/80763-crackerxi-decrypt-ios-apps-on-ios-10-11-12)

now that v12.4.1 is released, this issue can be closed!

**Comment by Jackiedk100** [comment]
> @daukstsoskars @Daemonceltics Please try Frida from git, which supports unc0ver (except for app launching).

When is app paunching going to work?
