### ISSUE TITLE
Android 8.1.0 can't attach to com.facebook.katana

### ISSUE THREAD

**Issue by begemot1451** [frida/frida#845]
```
$ frida -U -l __handlers__\xdev.js com.facebook.katana
     ____
    / _  |   Frida 12.4.0 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at http://www.frida.re/docs/home/
Failed to attach: timeout was reached
```

**Comment by enovella** [comment]
Hey @begemot1451,

Can you describe:
- Architecture used (x86, arm32 or aarch64)
- Share the JS code
- Try spawning instead of attaching
- Share the hash and apk sample

Best

**Comment by begemot1451** [comment]
>     * Architecture used (x86, arm32 or aarch64)
arm32
>     * Share the JS code
`
Java.perform(function() {
});
`
>     * Try spawning instead of attaching
```
$ frida -U -f com.facebook.katana --no-pause
     ____
    / _  |   Frida 12.4.0 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at http://www.frida.re/docs/home/
Failed to spawn: unable to access process with pid 495 due to system restrictions; try `sudo sysctl kernel.yama.ptrace_scope=0`, or run Frida as root

```
>     * Share the hash and apk sample
https://www.apkmirror.com/apk/facebook-2/facebook/facebook-216-0-0-38-104-release/facebook-216-0-0-38-104-android-apk-download/

**Comment by gorelics** [comment]
Hi, there are 3 possible issues: no root, Magisk 19, SELinux Enforcing

**Comment by begemot1451** [comment]
> Hi, there are 3 possible issues: no root, Magisk 19, SELinux Enforcing
Hi, no, i have root, Magisk 19, SELinux Permissive

On this device i can attach to any APK (snapchat, wechat, whatsapp) - no problem.
Impossible only com.facebook.katana and com.instagram.android ((

**Comment by stevepoland85** [comment]
Facebook has a billion dollar budget for their app. They probably employ some anti-debugging/anti-hooking/anti-frida stuff.

You may investigate it and figure out a bypass.

**Comment by begemot1451** [comment]
> 
> 
> Facebook has a billion dollar budget for their app. They probably employ some anti-debugging/anti-hooking/anti-frida stuff. (Intentional, or not due to the complexity of something they're doing)
> 
> You may investigate it and figure out a bypass.

On android 4.4.2-7.0 i have no problem with them. How can this be related?

**Comment by begemot1451** [comment]
> 
> 
> > Facebook has a billion dollar budget for their app. They probably employ some anti-debugging/anti-hooking/anti-frida stuff. (Intentional, or not due to the complexity of something they're doing)
> > You may investigate it and figure out a bypass.
> 
stevepoland85, On android 4.4.2-7.0 i have no problem with them. How can this be related?

**Comment by gorelics** [comment]
Try Magisk Only Core Option On

**Comment by begemot1451** [comment]
> 
> 
> Try Magisk Only Core Option On

@gorelics , no help :(

**Comment by gorelics** [comment]
Do other apps spawns with the frida -f flag? Or you can only attach to already running?

**Comment by begemot1451** [comment]
@gorelics , on Magisk 19 other apps NO spawns with -f (zigota bloked).
On Magisk 18.1 other apps spawns with -f , but facebook is crashed...

**Comment by gorelics** [comment]
Yes, I think there is no easy way, need to dive deep. Maybe JEB can help. I saw JEB 3 at hxxs://download.ir

**Comment by enovella** [comment]
> Facebook has a billion dollar budget for their app. They probably employ some anti-debugging/anti-hooking/anti-frida stuff. (Intentional, or not due to the complexity of something they're doing)
> 
> You may investigate it and figure out a bypass.

Let me check them out......

**Comment by begemot1451** [comment]
> Let me check them out......

@enovella , if it turns out I will be glad to feedback )

**Comment by therealbobo** [comment]
Same here for both Facebook and Instagram: I can spawn the process but the app freezes and the screen remains white.

**Comment by baptx** [comment]
I was not able to intercept HTTPS requests of the Instagram Android app (I did not test the Facebook app yet). I used mitmproxy and Android x86 on VirtualBox Host-Only adapter since Instagram is not working on Anbox.
Proxy was configured like this: `adb shell settings put global http_proxy 192.168.56.1:8080`.
I started frida like this: `adb shell "su 0 /data/local/tmp/frida-server -l 0.0.0.0" &` (0.0.0.0 is used to bypass a bug https://github.com/frida/frida/issues/92#issuecomment-441476989).
To disable certificate pinning I tried both Frida scripts (https://codeshare.frida.re/@sowdust/universal-android-ssl-pinning-bypass-2/ and https://codeshare.frida.re/@pcipolloni/universal-android-ssl-pinning-bypass-with-frida/) with these commands but the app freezes with a blank screen (with other Android apps it works):
`frida -H 192.168.56.102 -f com.instagram.android -l universal-ssl-check-bypass.js --no-pause`
`frida -H 192.168.56.102 -f com.instagram.android -l frida-android-repinning.js --no-pause`
Does someone have an idea why it fails and if there is a workaround? Please rename the issue to "Android can't attach to com.facebook.katana and com.instagram.android" since the issues happen with Android 7 too with both Facebook and Instagram apps.

**Comment by RoyalFlushever** [comment]
Downgrade your frida-server version on your android devices.
For example, if you have frida-version 10.6.32 on your PC, you can install frida-server 10.0.X.
Note: only master version should match between frida-server and frida.

**Comment by baptx** [comment]
@RoyalFlushever did Frida work for you on Facebook or Instagram? Which version did you use?

**Comment by baptx** [comment]
I found an article to disable certificate pining on Instagram Android app: https://plainsec.org/how-to-bypass-instagram-ssl-pinning-on-android-v78/
Is it possible to make this work as a Frida script?

**Comment by oleavr** [comment]
Please make sure you're running Frida >= 12.8.5 on both host and target. We have fixed a lot of bugs since this issue was reported.

If the issue persists it means it's a device-specific problem. If so, please file a new issue providing details about your device, ROM, and how you rooted it (if applicable).

Thanks everyone for reporting bugs and helping make Frida better! 🙌

**Comment by shehrozamin747** [comment]
i need a ssl pinning bypass frida script of wechat
