### ISSUE TITLE
Frida compatible with Chimera?  

### ISSUE THREAD

**Issue by JoeWHoward** [frida/frida#859]
iOS:  12.1.2
Processor:  A12
OS Version:  macOS Mojave 10.14
Jailbreak:  Chimera

`frida-ps -U`
`Failed to enumerate processes: the connection is closed `

Is Frida-tools from the repo compatible with Chimera jailbreak?

**Comment by karlek** [comment]
Yes, version 12.5 supports Chimera! 

> iOS
> The iOS Chimera jailbreak is also supported thanks to Francesco Tamagni’s awesome contributions. [1]

\[1\]: https://www.frida.re/news/2019/05/15/frida-12-5-released/

**Comment by xAiluros** [comment]
Just noticed that after updating chimera I could no longer spawn apps with frida, attaching to a running one worked fine. With chimera 1.0.6 and 1.0.7 frida-server got a segfault when trying to spawn.
Downgraded chimera to 1.0.4 and now spawning works fine again (with frida 12.6.5).
Since I am very new to working with iOS / jailbreaks and also frida I don't quite know where to start to fix this but maybe this will help someone at least.

**Comment by oleavr** [comment]
Just took a quick stab at fixing this, and it was as easy as I suspected: Frida 12.6.7 is currently being released with the [fix](https://github.com/frida/frida-core/commit/2fe99f8bc30fa0fc9c1c4b99bdada1d27bc936b5).

**Comment by Chvalov** [comment]
ios 12.5.5 / Chimera 1.6.4
The iPhone 5S restarts when the `frida-ps -U` command is running
```
Failed to enumerate processes: the connection is closed
```
