### ISSUE TITLE
problem with executable frida-server-12.6.10 : CANNOT LINK EXECUTABLE

### ISSUE THREAD

**Issue by syalosovetskyi** [frida/frida#948]
I try to open frida-server-12.6.10-android-arm on xperia c2305 (android 4.2.2)
But script failed with error: 
./frida-server-12.6.10-android-arm          
soinfo_relocate(linker.cpp:975): cannot locate symbol "getauxval" referenced by "./frida-server-12.6.10-android-arm"...CANNOT LINK EXECUTABLE
![image](https://user-images.githubusercontent.com/43996021/60816054-82562100-a1a1-11e9-8dd2-eba5dce701c8.png)

**Comment by parag85** [comment]
I am also facing the same issue with same frida server file. 

Device Name:  Samsung Tab 3 - OS - Android - 4.2.2.

![image](https://user-images.githubusercontent.com/8840359/61368832-5e36c600-a8ac-11e9-9641-8e47ed9c159c.png)

**Comment by x-serious** [comment]
yeah me two ffs fix this 0_x

**Comment by oleavr** [comment]
This is not a bug – you are using ancient versions of Android. The lowest supported version is Android 4.3, but these days virtually all testing happens on 9.0, so you better upgrade. (Unless you want to contribute to Frida to improve support for older versions.)

**Comment by aapo** [comment]
I found the last version which works with ancient Android-4.1.1.

The **frida-server-12.4.7-android-arm** is not giving error "cannot locate 'getauxval'"
https://github.com/frida/frida/releases/tag/12.4.7 

And it works with version (newest) frida-ps=12.9.7. (Nothing more tested)

frida-server-12.4.8-android-arm is giving "cannot locate 'getauxval'"
Between these versions there are 2478 commits.

I can't compile 12.4.7 for making bisect because old toolchain ( https://build.frida.re/toolchain-20180825-linux-x86_64.tar.bz2 ) is not in server anymore.

    git checkout 12.4.7
    export ANDROID_NDK_ROOT=~/android/tools/ndk/android-ndk-r17b/
    make server-android-arm

    Downloading and deploying toolchain...
    ( curl -sS https://build.frida.re/toolchain-20180825-linux-x86_64.tar.bz2 )
    bzip2: (stdin) is not a bzip2 file.

**Comment by oleavr** [comment]
@aapo Our 32-bit builds target API level >= 18, i.e. 4.3, so 4.1 is too old. Happy to revive support for it if you're interested in taking a stab at building our SDK (prebuilt deps) and figuring out what needs to be ported. Probably not too hard. I can't even remember at this point why I bumped the requirement to 18. Might have been something to do with PIE binary support.
