### ISSUE TITLE
failed to hook constructors in Android

### ISSUE THREAD

**Issue by litongxin1991** [frida/frida#98]
I tried to hook some constructors in Android, but it failed and the app usually crashed. 
The arguments and the return value are not right.

This is the sample code in an Android app
```
Class Test {
  int a;
  int b;
  int c;
  public Test(int x, int y, int z) {
    a = x;
    b = y;
    c = z;
  }
  public Test(int x) {...}
  public String toString() {
    return "" + a + " " + b + " " + c;
  }
};

Test test = new Test(12,34,56);
Log.d(TAG, test.toString());
```
I hooked the constructor in this way   
```
target.$new.overload("int","int", "int").implementation = function(arg0, arg1, arg2) {
        send("call " + arg0);
        send("call " + arg1);
        send("call " + arg2);
        ret = target.$new(7,7,7);
        send(ret.toString());
        return ret;
}
```

Actually, the function is called but the arguments and the return value are all wrong. 

```
Received from message:
{u'type': u'send', u'payload': u'call 34'}  //arg0
{u'type': u'send', u'payload': u'call 56'}  //arg1
{u'type': u'send', u'payload': u'call 1833118944'}  //arg2
{u'type': u'send', u'payload': u'7 7 7'}  //ret.toString()

logcat //Log.d(TAG, test.toString());
0 0 0
```
The arguments should be "12, 34, 56" not the "34, 56, 1833118944". In the function, I returned an object with "7 7 7", but the object the java code received was "0 0 0"

Thanks a lot!

**Comment by oleavr** [comment]
Hi,

Thanks for reporting. Which Android version are you trying this on?

**Comment by litongxin1991** [comment]
Android 4.4 on Nexus 5.
Thanks!

**Comment by oleavr** [comment]
Ok. Sounds like it should be easy to fix. I'm currently deep down in another part of Frida right now, so I can't look into this this week. Would you be interested in trying to track down the issue? What I usually do is the following:
- Copy-paste the contents of https://github.com/frida/frida-gum/blob/master/bindings/gumjs/gumjs-java.js into a new file locally, say `test.js`
- Rename the `Java` and `Dalvik` references [here](https://github.com/frida/frida-gum/blob/df1071108b08062f43e76bde89076f493ac602dc/bindings/gumjs/gumjs-java.js#L75-L89) to something else, say `JavaDev` and `DalvikDev`, making sure to update all three references there, lines 75, 84 and 87.
- Append my test-code to the very end of the file, remembering to use the new names from the previous step.
- Load this script into a running process: `frida -U com.foo.bar -l test.js`.
- Observe that the problem is reproduced.
- Study the source-code above, adding `console.log()` to better understand what's going on, and on every change just enter `%reload` in the REPL, which will reload the script from the filesystem. (No need to re-run the `frida` command.)

Feel like giving it a try?

**Comment by oleavr** [comment]
From a quick glance at your test outputs, I'm guessing that the problem is in this area:
https://github.com/frida/frida-gum/blob/df1071108b08062f43e76bde89076f493ac602dc/bindings/gumjs/gumjs-java.js#L1532
https://github.com/frida/frida-gum/blob/df1071108b08062f43e76bde89076f493ac602dc/bindings/gumjs/gumjs-java.js#L1584
The first two arguments are normally `env` and `this`, but for constructors it seems like the `this` argument is not there.

**Comment by litongxin1991** [comment]
I may find the cause.

I'm not familiar with the code, the fixes are incomplete and I only tested on the simple code above. But I hope the following information I found may help you. 

In dalvik byte code, the invocation to a constructor has two instructions.
```
new-instance v1, Ljava/lang/StringBuilder;
invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V
```
For the last instruction, it's similar to call a instance method. And the <init> function is what I tried to hook.
When the <init> function is called, there should be a this pointer. 
But the wrapper in frida combines the two instructions. The return type is the class, not the ```void``` and the method type is ```CONSTRUCTOR_METHOD```, not the ```INSTANCE_METHOD```.

In https://github.com/frida/frida-gum/blob/df1071108b08062f43e76bde89076f493ac602dc/bindings/gumjs/gumjs-java.js#L1309
I changed
```
if (type === INSTANCE_METHOD) {
  argsSize++;
}
==>
if (type === INSTANCE_METHOD **|| type === CONSTRUCTOR_METHOD** ) {
  argsSize++;
}
```


So the arguments received in the implement function is right.
It's because the ```this``` pointer should be an argument.

In https://github.com/frida/frida-gum/blob/df1071108b08062f43e76bde89076f493ac602dc/bindings/gumjs/gumjs-java.js#L1181
I changed 
```
type === INSTANCE_METHOD ? "this.$handle" : "this.$classHandle",
==>
(type === INSTANCE_METHOD || type === CONSTRUCTOR_METHOD)?"this.$handle" : "this.$classHandle"
```
And in https://github.com/frida/frida-gum/blob/df1071108b08062f43e76bde89076f493ac602dc/bindings/gumjs/gumjs-java.js#L1537
```
"const self = " + ((type === INSTANCE_METHOD) ? "new C(C.__handle__, thisHandle);" : "new C(thisHandle, null);")
==>
"const self = " + ((type === INSTANCE_METHOD || type === CONSTRUCTOR_METHOD) ? "new C(C.__handle__, thisHandle);" : "new C(thisHandle, null);") +
```

This will pass the this handler to <init> function.
So one can modify the ```this``` object in the``` implement``` funciton.
And there is no need to return an object in the hooked constructor.

But the origin ```<init>``` function still can't be called from the ```implement``` function

**Comment by oleavr** [comment]
Cool, this is great progress! On Dalvik we handle the "calling back to the original function" by the following trick at the VM level:
- Make a shallow copy of the class structure, except for the vtable, which we copy. This is our shadow version of the class.
- Update the original's vtable so it has our replacement implementation
- Leave the copy with the original implementation
- Pass the shadow class to our callback, so that if we try to call the same method from inside our implementation it will call the original instead of recursing back to ourself.

Perhaps this logic isn't working for constructors? (Maybe they're not in the vtable – didn't check that.)

**Comment by pandasauce** [comment]
duplicate https://github.com/frida/frida-gum/issues/89

**Comment by litongxin1991** [comment]
Sorry, the code above should not be changed in https://github.com/frida/frida-gum/blob/df1071108b08062f43e76bde89076f493ac602dc/bindings/gumjs/gumjs-java.js#L1537
```
"const self = " + ((type === INSTANCE_METHOD) ? "new C(C.__handle__, thisHandle);" : "new C(thisHandle, null);")
```
Otherwise, the ```$new``` can't be called in the script.

Actually, the origin ```$new``` function can be called. But it doesn't make any changes to the ```this``` pointer.  Maybe it's because that the ```<init>``` function is used for initializing ```this``` pointer after the object is alloced, while the ```$new``` is used for created a new object and initializing it.

**Comment by oleavr** [comment]
Let's keep tracking this in frida/frida-gum#89.
