### ISSUE TITLE
fork support

### ISSUE THREAD

**Issue by bannsec** [frida/frida#988]
Is attaching to child after a fork call supported? Presuming that I'm already connected to the parent and run fork().

If no direct support, would there be some reasonable workaround?

**Comment by oleavr** [comment]
Yes, see the child-gating example in frida-python. (For now you cannot call `fork()` from any of Frida's threads, only the application is expected to call it.)

**Comment by bannsec** [comment]
Ah. The later case is actually what I'm attempting. The goal being to be able to fork off a new copy, attach to it as well, and run something that may well crash the sub process.

Is there any possible workaround for this that would not involve a full program re-load?

**Comment by oleavr** [comment]
No, you would either need cooperation from the application, or it has to be a really simple single-threaded application. Otherwise all bets are off. E.g. the app might be holding a lock in one of its threads. When you `fork()`, the copy will only contain the thread calling `fork()`, and the app thread that took the lock is not around anymore so the lock might now be held forever, and if you call an API that needs to acquire the lock you will end up with a deadlock. So no, this is not going to work unless you make a lot of assumptions about the particular application. But if you can, and see a way to handle this (see the fork-handling in `frida-core/lib/agent/agent.vala`), I'm happy to accept PRs adding support for it.
