### ISSUE TITLE
Java.choose now returns unsupported

### ISSUE THREAD

**Issue by bannsec** [frida/frida#989]
I'm attempting to run `Java.choose` against a basic app on an Android x86_64 emulator. This previously worked, however after some update (don't know which one) this stopped working, and now returns 'unsupported' errors.

```
$ frida -U com.android.messaging
     ____
    / _  |   Frida 12.6.16 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at http://www.frida.re/docs/home/

[Android Emulator 5554::com.android.messaging]-> Java.perform( function () { console.log (Java.enumerateLoadedClassesSync()) } )
<whole bunch of classes here>
[Android Emulator 5554::com.android.messaging]-> Java.perform(function () { Java.choose('com.android.internal.logging.MetricsLogger', { onMatch: function (i) { console.log('here'); }, onComplete: function () {}})})
Error: unsupported
    at o (/_java.js:191)
    at frida/node_modules/frida-java-bridge/lib/class-factory.js:196
    at frida/node_modules/frida-java-bridge/lib/class-factory.js:190
    at chooseObjectsArtModern (frida/node_modules/frida-java-bridge/lib/class-factory.js:22)
    at frida/node_modules/frida-java-bridge/lib/class-factory.js:138
    at ve (frida/node_modules/frida-java-bridge/lib/android.js:845)
```

It definitely used to work like that for basic applications on the emulator, and now they all seem to return unsupported. I don't think I changed anything about my emulator.

**Comment by bannsec** [comment]
Ok, so after testing, it looks like the last version this worked in was `12.6.11`, and it started failing in `12.6.12`.

**Comment by oleavr** [comment]
Thanks for reporting! This does indeed look like a regression.

/cc @gebing.

**Comment by gebing** [comment]
@oleavr 
I test on Android's Pixel2 x86_64 emulator of API 25, with the same target app and the same commands. But it works find and can not reproduce the same error.

**Comment by bannsec** [comment]
Perhaps it's the API version?

My emulator is `system-images;android-27;default;x86_64`. Full setup details here: 

https://travis-ci.org/bannsec/frida-util/jobs/573648762/config

**Comment by bannsec** [comment]
I've created and pushed a docker environment to load up this emulator:

```
sudo docker run -it --network host --name frida_android_choose --privileged -e DISPLAY=$DISPLAY -v /tmp/.X11-unix/:/tmp/.X11-unix/ --device /dev/kvm bannsec/frida_android_choose
```

To run it:
```
/root/Android/Sdk/emulator/emulator @test
```

**Comment by gebing** [comment]
@bannsec 
Pull docker image failed.

```
docker run -it --network host --name frida_android_choose --privileged -e DISPLAY=$DISPLAY -v /tmp/.X11-unix/:/tmp/.X11-unix/ --device /dev/kvm bannsec/frida_android_choose
Unable to find image 'bannsec/frida_android_choose:latest' locally
latest: Pulling from bannsec/frida_android_choose
898c46f3b1a1: Pulling fs layer
63366dfa0a50: Pulling fs layer
041d4cd74a92: Downloading
6e1bee0f8701: Waiting
be53e09ffa82: Waiting
71470174e979: Waiting
f737cc5a7269: Waiting
docker: Get https://registry-1.docker.io/v2/bannsec/frida_android_choose/manifests/latest: unauthorized: incorrect username or password.
See 'docker run --help'.
```

**Comment by bannsec** [comment]
Not sure. Sometimes just retrying it works. It's definitely not a private
image.

Otherwise, the only thing I did to setup was open up avd manager for
android and install x86_64 api version 27 without the Google bindings.
Everything on the install is default.

**Comment by bannsec** [comment]
Just tested:

 - API 25 == Works
 - API 27 == Fail

Haven't had a chance to test others, but it appears the API version is important.

**Comment by gebing** [comment]
I finally found the bug for this issue, it is caused by duktape's `Reflect.get()`'s restriction.

duktape's `Reflect.get()` do not support parameter `receiver` currently, and if it is called with parameter `receiver`, it must be same as `target`, otherwise will throw an error of 'unsupported'. The code of duktape is [https://github.com/svaarala/duktape/blob/master/src-input/duk_bi_reflect.c](https://github.com/svaarala/duktape/blob/master/src-input/duk_bi_reflect.c) 

But why frida only failed on Android API 27? 

It is because that the reference of `Reflect` only exists in `java.js` of duptake runtime, and `Reflect.get()` will be called only when javascript invoke method of `super` , such as code below:

```
init (thread) {
  const topHandleScopePtr = thread.add(getArtThreadSpec(vm).offset.topHandleScope);
  this._topHandleScopePtr = topHandleScopePtr;

  super.init(topHandleScopePtr.readPointer(), kNumReferencesVariableSized);

  this.self = thread;
  this.currentScope = FixedSizeHandleScope.$new(this._scopeLayout);

  topHandleScopePtr.writePointer(this);
}
```

On android prior to API 27, the frida will not invoke method of `super`, because the code below will goto `chooseObjectsArtLegacy` and not `chooseObjectsArtModern`:

```
this.choose = function (specifier, callbacks) {
  if (api.flavor === 'art') {
    const env = vm.getEnv();
    withRunnableArtThread(vm, env, thread => {
      if (api['art::gc::Heap::VisitObjects'] === undefined) {
        chooseObjectsArtModern(env, thread, specifier, callbacks);
      } else {
        chooseObjectsArtLegacy(env, thread, specifier, callbacks);
      }
    });
  } else {
    chooseObjectsDalvik(specifier, callbacks);
  }
};
```

@oleavr 
I will make a new Issue and Pull request in frida-java-bridge.

**Comment by gebing** [comment]
@oleavr 
I made a pull request for frida-gum, #345. I think it should be a common patch for duktape runtime.

**Comment by oleavr** [comment]
@gebing Thanks a lot for tracking this one down!

I gave it some thought and realized that this is the same kind of issue as we were dealing with in 83e98b4, so I figured it's better to disable the builtin instead. This way, since we're using `frida-compile` w/Babel under the hood, its polyfill will use its fully standard-compliant version instead of the non-standard one built into Duktape.
